"""Activation/deactivation file signature integrity (21 CFR Part 11 §11.10(e)).

Files generated by the Cassini machine flow operator -> portal. To prevent
forgery and tamper-in-flight, each file is Ed25519-signed by a per-instance
keypair. Legacy unsigned (version<2) files MUST be rejected by both sides.
"""

from __future__ import annotations

import json as _json
import base64
from datetime import datetime, timedelta, timezone
from unittest.mock import PropertyMock

import jwt
import pytest
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from cryptography.hazmat.primitives.serialization import (
    Encoding,
    NoEncryption,
    PrivateFormat,
    PublicFormat,
)

from cassini.core.licensing import LicenseService


@pytest.fixture
def ed25519_keypair():
    """Generate a test Ed25519 keypair for signing license JWTs."""
    private_key = Ed25519PrivateKey.generate()
    public_key = private_key.public_key()
    private_pem = private_key.private_bytes(
        Encoding.PEM, PrivateFormat.PKCS8, NoEncryption()
    )
    public_pem = public_key.public_bytes(
        Encoding.PEM, PublicFormat.SubjectPublicKeyInfo
    )
    return private_pem, public_pem


@pytest.fixture
def make_license(ed25519_keypair, tmp_path):
    """Factory to create signed license files."""
    private_pem, public_pem = ed25519_keypair

    def _make(claims: dict, filename: str = "license.key"):
        token = jwt.encode(claims, private_pem, algorithm="EdDSA")
        license_path = tmp_path / filename
        license_path.write_text(token)
        return license_path, public_pem

    return _make


@pytest.fixture
def patched_data_dir(tmp_path, monkeypatch):
    """Patch LicenseService._data_dir to a temp dir so the per-instance
    activation key is created in isolation per test."""
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    monkeypatch.setattr(
        LicenseService, "_data_dir", PropertyMock(return_value=data_dir),
    )
    return data_dir


@pytest.fixture
def valid_claims():
    return {
        "sub": "acme-corp",
        "tier": "enterprise",
        "max_plants": 20,
        "expires_at": (datetime.now(timezone.utc) + timedelta(days=365)).isoformat(),
    }


def test_activation_file_is_signed_and_verifiable(
    make_license, valid_claims, patched_data_dir
) -> None:
    """Round-trip: generate a signed activation file, then verify it."""
    path, pub = make_license(valid_claims)
    svc = LicenseService(license_path=str(path), public_key=pub)

    envelope = svc.generate_activation_file()

    # Envelope contains the signature fields
    assert envelope["signatureAlgorithm"] == "Ed25519"
    assert envelope["version"] >= 2
    assert envelope["signature"]
    assert envelope["publicKey"]

    # Verification round-trips and returns the inner payload
    payload = LicenseService.verify_activation_file(envelope)
    assert payload["type"] == "cassini-activation"
    assert payload["licenseId"] == "acme-corp"
    assert payload["instanceId"] == svc.instance_id


def test_deactivation_file_is_signed_and_verifiable(
    make_license, valid_claims, patched_data_dir
) -> None:
    path, pub = make_license(valid_claims)
    svc = LicenseService(license_path=str(path), public_key=pub)

    envelope = svc.generate_deactivation_file()
    assert envelope is not None

    payload = LicenseService.verify_activation_file(envelope)
    assert payload["type"] == "cassini-deactivation"
    assert payload["licenseId"] == "acme-corp"


def test_unsigned_activation_file_is_rejected() -> None:
    """Legacy v1 (unsigned) files MUST be rejected outright."""
    legacy = {
        "type": "cassini-activation",
        "version": 1,  # <-- unsigned legacy format
        "licenseId": "acme-corp",
        "instanceId": "host-1",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    with pytest.raises(ValueError, match="unsigned"):
        LicenseService.verify_activation_file(legacy)


def test_tampered_activation_file_is_rejected(
    make_license, valid_claims, patched_data_dir
) -> None:
    """Modifying any payload field after signing must invalidate the signature."""
    path, pub = make_license(valid_claims)
    svc = LicenseService(license_path=str(path), public_key=pub)

    envelope = svc.generate_activation_file()
    # Tamper: change instanceId in flight
    envelope["instanceId"] = "MITM-INJECTED"

    with pytest.raises(ValueError, match="signature is invalid"):
        LicenseService.verify_activation_file(envelope)


def test_wrong_algorithm_is_rejected() -> None:
    """Only Ed25519 envelopes are accepted."""
    bogus = {
        "type": "cassini-activation",
        "version": 2,
        "licenseId": "acme",
        "instanceId": "host",
        "timestamp": "2025-01-01T00:00:00+00:00",
        "signature": base64.b64encode(b"x" * 64).decode("ascii"),
        "publicKey": "-----BEGIN PUBLIC KEY-----\nfake\n-----END PUBLIC KEY-----\n",
        "signatureAlgorithm": "RSA-PSS",
    }
    with pytest.raises(ValueError, match="Unsupported signature algorithm"):
        LicenseService.verify_activation_file(bogus)


def test_missing_signature_fields_are_rejected() -> None:
    """A v2-claiming envelope without signature/publicKey is rejected."""
    incomplete = {
        "type": "cassini-activation",
        "version": 2,
        "licenseId": "acme",
        "instanceId": "host",
        "timestamp": "2025-01-01T00:00:00+00:00",
        # signature and publicKey deliberately missing
    }
    with pytest.raises(ValueError, match="missing signature or public key"):
        LicenseService.verify_activation_file(incomplete)


def test_envelope_canonical_serialization_is_stable(
    make_license, valid_claims, patched_data_dir
) -> None:
    """Re-serializing the file via JSON.parse/JSON.stringify must still verify.

    This exercises the property the portal-side TS verifier depends on:
    the canonical JSON serialization (sorted keys, no whitespace) is stable
    across language boundaries.
    """
    path, pub = make_license(valid_claims)
    svc = LicenseService(license_path=str(path), public_key=pub)

    envelope = svc.generate_activation_file()
    # Round-trip through JSON (as the operator's browser would do)
    rehydrated = _json.loads(_json.dumps(envelope))
    payload = LicenseService.verify_activation_file(rehydrated)
    assert payload["licenseId"] == "acme-corp"
