"""Show Your Work — Explain API.

Returns step-by-step formula breakdowns for statistical metrics,
generated by the same engine code that computed the values.
"""

import logging
import math
from datetime import datetime, timezone

import numpy as np
from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from cassini.api.deps import (
    check_plant_role,
    get_current_user,
    get_db_session,
    resolve_plant_id_for_characteristic,
)
from cassini.api.schemas.explain import CitationSchema, ExplanationResponse, ExplanationStepSchema
from cassini.core.capability import calculate_capability_async
from cassini.core.engine.attribute_engine import calculate_attribute_limits, calculate_laney_sigma_z
from cassini.core.explain import (
    ATTRIBUTE_MSA_CITATION,
    CAPABILITY_CITATION,
    Citation,
    ExplanationCollector,
    MSA_CITATION,
)
from cassini.core.msa import AttributeMSAEngine, GageRREngine
from cassini.db.models.msa import MSAMeasurement, MSAOperator, MSAPart, MSAStudy
from cassini.db.models.user import User
from cassini.db.repositories.sample import SampleRepository
from cassini.utils.constants import get_c4, get_d2

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/explain", tags=["explain"])

# Metric type -> display name + general formula
METRIC_DEFINITIONS = {
    "cp": ("Process Potential (Cp)", r"C_p = \frac{USL - LSL}{6\sigma_w}"),
    "cpk": (
        "Process Capability (Cpk)",
        r"C_{pk} = \min\left(\frac{USL - \bar{x}}{3\sigma_w}, \frac{\bar{x} - LSL}{3\sigma_w}\right)",
    ),
    "pp": ("Process Performance (Pp)", r"P_p = \frac{USL - LSL}{6\sigma_{overall}}"),
    "ppk": (
        "Process Performance (Ppk)",
        r"P_{pk} = \min\left(\frac{USL - \bar{x}}{3\sigma_{overall}}, \frac{\bar{x} - LSL}{3\sigma_{overall}}\right)",
    ),
    "cpm": (
        "Taguchi Capability (Cpm)",
        r"C_{pm} = \frac{USL - LSL}{6\tau}, \quad \tau = \sqrt{\sigma_w^2 + (\bar{x} - T)^2}",
    ),
}

CAPABILITY_METRICS = {"cp", "cpk", "pp", "ppk", "cpm"}

# Step label prefixes relevant to each metric. Filters the collector's
# full step list down to only the computation chain for the requested metric.
METRIC_STEP_PREFIXES: dict[str, list[str]] = {
    "cp": ["Normality", "Cp (", "Z.Bench"],
    "cpk": ["Normality", "Cpu", "Cpl", "Cpk", "Z.Bench"],
    "pp": ["Normality", "Pp (", "Z.Bench"],
    "ppk": ["Normality", "Ppu", "Ppl", "Ppk", "Z.Bench"],
    "cpm": ["Normality", "Cp (", "\u03c4", "Cpm", "Z.Bench"],
}


@router.get(
    "/capability/{metric_type}/{characteristic_id}",
    response_model=ExplanationResponse,
)
async def explain_capability_metric(
    metric_type: str,
    characteristic_id: int,
    limit: int | None = Query(None, ge=2, le=10000, description="Max samples (matches dashboard limit)"),
    start_date: str | None = Query(None, description="ISO start date (matches dashboard range)"),
    end_date: str | None = Query(None, description="ISO end date (matches dashboard range)"),
    material_id: int | None = Query(None, description="Material ID for material-specific capability"),
    db: AsyncSession = Depends(get_db_session),
    current_user: User = Depends(get_current_user),
):
    """Return step-by-step explanation of a capability metric.

    Pass the same limit/start_date/end_date the dashboard uses so the
    explanation matches the displayed value exactly.
    """
    if metric_type not in CAPABILITY_METRICS:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unknown capability metric: {metric_type}",
        )

    # Plant RBAC check (resolve plant_id through hierarchy)
    plant_id = await resolve_plant_id_for_characteristic(characteristic_id, db)
    check_plant_role(current_user, plant_id, "operator")

    # Load characteristic
    from sqlalchemy import select as sa_select

    from cassini.db.models.characteristic import Characteristic

    stmt = sa_select(Characteristic).where(Characteristic.id == characteristic_id)
    result = await db.execute(stmt)
    char = result.scalar_one_or_none()
    if char is None:
        raise HTTPException(status_code=404, detail="Characteristic not found")

    # Only variable charts support capability explanation
    if char.data_type == "attribute":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Capability analysis is not supported for attribute charts",
        )

    # Resolve material-specific spec limits and sigma
    _eff_usl = char.usl
    _eff_lsl = char.lsl
    _eff_target = char.target_value
    _eff_stored_sigma = char.stored_sigma

    if material_id:
        from cassini.core.material_resolver import MaterialResolver
        _resolver = MaterialResolver(db)
        _char_defaults = {
            "ucl": char.ucl, "lcl": char.lcl,
            "stored_sigma": char.stored_sigma,
            "stored_center_line": char.stored_center_line,
            "target_value": char.target_value,
            "usl": char.usl, "lsl": char.lsl,
        }
        _resolved = await _resolver.resolve_flat(characteristic_id, material_id, _char_defaults)
        if _resolved["usl"] is not None:
            _eff_usl = _resolved["usl"]
        if _resolved["lsl"] is not None:
            _eff_lsl = _resolved["lsl"]
        if _resolved["target_value"] is not None:
            _eff_target = _resolved["target_value"]
        if _resolved["stored_sigma"] is not None:
            _eff_stored_sigma = _resolved["stored_sigma"]

    if _eff_usl is None and _eff_lsl is None:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="At least one specification limit (USL or LSL) must be set",
        )

    # Two modes of operation:
    # 1. With chart options (start_date/end_date/limit) — caller is displaying
    #    a chart view with subgroup means.  Use subgroup means + sigma of means.
    # 2. Without chart options — matches the capability GET endpoint, which
    #    flattens individual measurements and uses stored_sigma (R-bar/d2).
    repo = SampleRepository(db)
    has_chart_options = bool(start_date or end_date or limit)

    if has_chart_options:
        # Chart-view mode: fetch samples matching the caller's filter and
        # compute subgroup means — matching the chart's data_points[].mean.
        #
        # IMPORTANT: When called with limit-only (no date range), we MUST use
        # the same query the dashboard uses (get_rolling_window_data) so the
        # explained Cpk matches the displayed Cpk.  When start_date/end_date
        # are given, we use get_by_characteristic with date filtering.
        if start_date or end_date:
            # Date-filtered branch — normalize naive ISO strings to UTC so
            # SQLite's timezone-stripping comparison returns the right rows.
            # SQLite drops tzinfo on storage, so naive vs aware comparison
            # silently yields wrong samples.  Pattern from correlation.py:332.
            sd = datetime.fromisoformat(start_date) if start_date else None
            if sd is not None and sd.tzinfo is None:
                sd = sd.replace(tzinfo=timezone.utc)
            ed = datetime.fromisoformat(end_date) if end_date else None
            if ed is not None and ed.tzinfo is None:
                ed = ed.replace(tzinfo=timezone.utc)
            samples = await repo.get_by_characteristic(
                char_id=characteristic_id,
                start_date=sd,
                end_date=ed,
                material_id=material_id,
            )
            # Filter excluded samples (get_by_characteristic doesn't do this)
            samples = [s for s in samples if not s.is_excluded]
            # Apply limit (most recent N within the range)
            if limit and len(samples) > limit:
                samples = samples[-limit:]
            # Compute subgroup means
            values: list[float] = []
            for s in samples:
                meas = [m.value for m in s.measurements]
                if meas:
                    values.append(sum(meas) / len(meas))
        else:
            # Limit-only branch — use the same query the dashboard's chart
            # endpoint uses (get_rolling_window with window_size=limit) so
            # values match exactly.  Diverging from this caused C14: any
            # excluded sample produced a different displayed vs explained Cpk.
            window_data = await repo.get_rolling_window_data(
                char_id=characteristic_id,
                window_size=limit or 50,
                exclude_excluded=True,
                material_id=material_id,
            )
            # Compute subgroup means from per-sample values
            values: list[float] = []
            for sd_item in window_data:
                meas = sd_item["values"]
                if meas:
                    values.append(sum(meas) / len(meas))
    else:
        # No chart options — match the capability GET endpoint exactly.
        # CapabilityCard and dashboard Cpk pill use this path.
        sample_data = await repo.get_rolling_window_data(
            char_id=characteristic_id,
            window_size=1000,
            exclude_excluded=True,
            material_id=material_id,
        )
        values = []
        for sd_item in sample_data:
            values.extend(sd_item["values"])

    if len(values) < 2:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Need at least 2 measurements",
        )

    # Sigma strategy: when called with chart options (matching a dashboard view),
    # compute sigma from the subgroup means — this is exactly what the dashboard
    # does in its quickStats useMemo.  Without chart options (e.g. from
    # CapabilityCard), use stored_sigma (R-bar/d2) for AIAG-correct Cpk.
    sigma_fallback = False
    if has_chart_options:
        # Match dashboard: sigma = sample std dev of subgroup means
        sigma_within = float(np.std(np.asarray(values, dtype=np.float64), ddof=1))
        sigma_fallback = True
        sigma_estimator = "sample_std_dev"
    else:
        sigma_within = _eff_stored_sigma
        if sigma_within is None or sigma_within <= 0:
            sigma_within = float(np.std(np.asarray(values, dtype=np.float64), ddof=1))
            sigma_fallback = True
            sigma_estimator = "sample_std_dev"
        else:
            # Derive method from subgroup size (matches control limits logic)
            n = char.subgroup_size
            if n == 1:
                sigma_estimator = "moving_range"
            elif n <= 10:
                sigma_estimator = "r_bar_d2"
            else:
                sigma_estimator = "s_bar_c4"

    # Run capability with collector
    collector = ExplanationCollector()
    if has_chart_options:
        collector.warn(
            "Dashboard view: using sample \u03c3 of subgroup means, so Cp/Cpk will "
            "equal Pp/Ppk.  For AIAG-correct Cp/Cpk (within-subgroup \u03c3), "
            "see the Capability Card which uses stored \u03c3_w (R-bar/d2)."
        )
    elif sigma_fallback:
        collector.warn(
            "Within-subgroup sigma (\u03c3_w) not stored \u2014 using sample standard "
            "deviation as estimate. Cp/Cpk values equal Pp/Ppk."
        )
    # Thread subgroup structure for correct Cp CI degrees of freedom
    # (ISO 22514-2:2017 §7.2.3).  Only applicable in the non-chart-options
    # path where values are individual measurements from real subgroups.
    # In the chart-options path, values ARE subgroup means so df=n-1 is
    # already correct — we omit subgroup params to trigger the fallback.
    _sg_count: int | None = None
    _sg_size: int | None = None
    if not has_chart_options:
        _sg_count = len(sample_data) if sample_data else None
        _sg_size = char.subgroup_size

    cap_result = await calculate_capability_async(
        values=values,
        usl=_eff_usl,
        lsl=_eff_lsl,
        target=_eff_target,
        sigma_within=sigma_within,
        collector=collector,
        subgroup_count=_sg_count,
        subgroup_size=_sg_size,
    )

    # Extract the requested metric value
    metric_value = getattr(cap_result, metric_type, None)
    if metric_value is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Cannot compute {metric_type} -- check specification limits and data",
        )

    display_name, formula_latex = METRIC_DEFINITIONS[metric_type]

    # Filter steps to only those relevant to the requested metric
    prefixes = METRIC_STEP_PREFIXES.get(metric_type, [])
    relevant_steps = [
        s
        for s in collector.steps
        if any(s.label.startswith(p) for p in prefixes)
    ]

    return ExplanationResponse(
        metric=metric_type,
        display_name=display_name,
        value=metric_value,
        formula_latex=formula_latex,
        steps=[
            ExplanationStepSchema(
                label=s.label,
                formula_latex=s.formula_latex,
                substitution_latex=s.substitution_latex,
                result=s.result,
                note=s.note,
            )
            for s in relevant_steps
        ],
        inputs=collector.inputs,
        citation=CitationSchema(
            standard=CAPABILITY_CITATION.standard,
            reference=CAPABILITY_CITATION.reference,
            section=CAPABILITY_CITATION.section,
        ),
        method="normal",
        sigma_estimator=sigma_estimator,
        warnings=collector.warnings,
    )


# ---------------------------------------------------------------------------
# Control Limits explanation
# ---------------------------------------------------------------------------

CONTROL_LIMITS_CITATION = Citation(
    standard="AIAG",
    reference="AIAG SPC Manual, 2nd Edition",
    section="Chapter 2: Control Charts",
)

CONTROL_LIMITS_METRICS = {"ucl", "lcl", "center_line", "sigma"}

CONTROL_LIMITS_DEFINITIONS: dict[str, tuple[str, str]] = {
    "ucl": ("Upper Control Limit (UCL)", r"UCL = \bar{\bar{x}} + 3\sigma_{\bar{x}}"),
    "lcl": ("Lower Control Limit (LCL)", r"LCL = \bar{\bar{x}} - 3\sigma_{\bar{x}}"),
    "center_line": ("Center Line", r"CL = \bar{\bar{x}}"),
    "sigma": ("Process Sigma (\u03c3)", r"\sigma = \frac{\bar{R}}{d_2}"),
}

CONTROL_LIMITS_STEP_PREFIXES: dict[str, list[str]] = {
    "ucl": ["X", "σ", "UCL"],
    "lcl": ["X", "σ", "LCL"],
    "center_line": ["X", "σ"],
    "sigma": ["σ"],
}


# ---------------------------------------------------------------------------
# Attribute SPC constants
# ---------------------------------------------------------------------------

ATTRIBUTE_SPC_CITATION = Citation(
    standard="AIAG",
    reference="AIAG SPC Manual, 2nd Edition",
    section="Chapter 4: Attribute Control Charts",
)

ATTRIBUTE_METRICS = {"center_line", "ucl", "lcl", "sigma_z"}

ATTRIBUTE_METRIC_DEFINITIONS: dict[str, tuple[str, str]] = {
    "center_line": ("Center Line", r"\bar{p}, \bar{c}, \text{or } \bar{u}"),
    "ucl": ("Upper Control Limit", r"UCL = \bar{p} + 3\sigma"),
    "lcl": ("Lower Control Limit", r"LCL = \max(0, \bar{p} - 3\sigma)"),
    "sigma_z": ("Laney Correction (\u03c3_z)", r"\sigma_z = \frac{\overline{MR}_Z}{d_2}"),
}

ATTRIBUTE_STEP_PREFIXES: dict[str, list[str]] = {
    "center_line": ["p-bar", "np-bar", "c-bar", "u-bar", "Center", "total"],
    "ucl": ["p-bar", "np-bar", "c-bar", "u-bar", "Center", "total", "\u03c3", "sigma", "UCL", "n-bar"],
    "lcl": ["p-bar", "np-bar", "c-bar", "u-bar", "Center", "total", "\u03c3", "sigma", "LCL", "n-bar"],
    "sigma_z": ["Z_i", "MR", "d2", "\u03c3_z", "sigma_z"],
}


@router.get(
    "/control-limits/{metric_type}/{characteristic_id}",
    response_model=ExplanationResponse,
)
async def explain_control_limits_metric(
    metric_type: str,
    characteristic_id: int,
    material_id: int | None = Query(None, description="Material ID for material-specific limits"),
    db: AsyncSession = Depends(get_db_session),
    current_user: User = Depends(get_current_user),
):
    """Return step-by-step explanation of a control limit metric.

    Uses stored values (sigma, center_line, UCL, LCL) directly rather than
    replaying calculations. This guarantees the explanation matches the
    displayed values exactly, regardless of when limits were set or how
    many samples have been added since.
    """
    if metric_type not in CONTROL_LIMITS_METRICS:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unknown control limits metric: {metric_type}",
        )

    # Plant RBAC check
    plant_id = await resolve_plant_id_for_characteristic(characteristic_id, db)
    check_plant_role(current_user, plant_id, "operator")

    # Load characteristic
    from sqlalchemy import select as sa_select

    from cassini.db.models.characteristic import Characteristic

    stmt = sa_select(Characteristic).where(Characteristic.id == characteristic_id)
    result = await db.execute(stmt)
    char = result.scalar_one_or_none()
    if char is None:
        raise HTTPException(status_code=404, detail="Characteristic not found")

    # Only variable charts support control limit explanation
    if char.data_type == "attribute":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Control limit explanation is not supported for attribute charts",
        )

    # Read stored values — these are the source of truth
    stored_sigma = char.stored_sigma
    stored_center = char.stored_center_line
    stored_ucl = char.ucl
    stored_lcl = char.lcl
    subgroup_size = char.subgroup_size
    short_run_mode = getattr(char, "short_run_mode", None)
    target_value = char.target_value

    # Resolve material-specific overrides
    if material_id:
        from cassini.core.material_resolver import MaterialResolver
        _resolver = MaterialResolver(db)
        _char_defaults = {
            "ucl": char.ucl, "lcl": char.lcl,
            "stored_sigma": stored_sigma,
            "stored_center_line": stored_center,
            "target_value": target_value,
            "usl": char.usl, "lsl": char.lsl,
        }
        _resolved = await _resolver.resolve_flat(characteristic_id, material_id, _char_defaults)
        if _resolved["stored_sigma"] is not None:
            stored_sigma = _resolved["stored_sigma"]
        if _resolved["stored_center_line"] is not None:
            stored_center = _resolved["stored_center_line"]
        if _resolved["target_value"] is not None:
            target_value = _resolved["target_value"]
        if _resolved.get("ucl") is not None:
            stored_ucl = _resolved["ucl"]
        if _resolved.get("lcl") is not None:
            stored_lcl = _resolved["lcl"]

    if stored_sigma is None or stored_center is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="No stored control limits to explain — recalculate limits first",
        )

    # Determine method from subgroup size
    if subgroup_size == 1:
        method = "moving_range"
    elif subgroup_size <= 10:
        method = "r_bar_d2"
    else:
        method = "s_bar_c4"

    # Build explanation from stored values (no sample queries needed)
    collector = ExplanationCollector()

    # Record inputs
    collector.input("n (subgroup size)", subgroup_size)
    collector.input("σ (stored process sigma)", round(stored_sigma, 6))
    collector.input("Center line (stored)", round(stored_center, 6))

    # Step 1: Show sigma source based on method
    if method == "moving_range":
        d2 = get_d2(2)
        mr_bar = stored_sigma * d2  # reverse: sigma = MR-bar / d2
        collector.step(
            label="σ (Process Sigma) — from stored MR-bar/d2",
            formula_latex=r"\sigma = \frac{\overline{MR}}{d_2}",
            substitution_latex=(
                r"\sigma = \frac{"
                + str(round(mr_bar, 6))
                + r"}{"
                + str(d2)
                + r"}"
            ),
            result=stored_sigma,
            note="Stored from last limit calculation (I-MR method, d₂=1.128 for span=2)",
        )
    elif method == "r_bar_d2":
        d2 = get_d2(subgroup_size)
        r_bar = stored_sigma * d2  # reverse: sigma = R-bar / d2
        collector.step(
            label="σ (Process Sigma) — from stored R-bar/d2",
            formula_latex=r"\sigma = \frac{\bar{R}}{d_2}",
            substitution_latex=(
                r"\sigma = \frac{"
                + str(round(r_bar, 6))
                + r"}{"
                + str(d2)
                + r"}"
            ),
            result=stored_sigma,
            note=f"Stored from last limit calculation (R-bar/d₂ method, n={subgroup_size})",
        )
    else:  # s_bar_c4
        c4 = get_c4(subgroup_size)
        s_bar = stored_sigma * c4  # reverse: sigma = S-bar / c4
        collector.step(
            label="σ (Process Sigma) — from stored S-bar/c4",
            formula_latex=r"\sigma = \frac{\bar{S}}{c_4}",
            substitution_latex=(
                r"\sigma = \frac{"
                + str(round(s_bar, 6))
                + r"}{"
                + str(c4)
                + r"}"
            ),
            result=stored_sigma,
            note=f"Stored from last limit calculation (S-bar/c₄ method, n={subgroup_size})",
        )

    # Step 2: Sigma of the mean (for subgroups > 1)
    if subgroup_size > 1:
        sigma_xbar = stored_sigma / math.sqrt(subgroup_size)
        collector.step(
            label="σ_x̄ (Sigma of the Mean)",
            formula_latex=r"\sigma_{\bar{x}} = \frac{\sigma}{\sqrt{n}}",
            substitution_latex=(
                r"\sigma_{\bar{x}} = \frac{"
                + str(round(stored_sigma, 6))
                + r"}{\sqrt{"
                + str(subgroup_size)
                + r"}}"
            ),
            result=sigma_xbar,
        )
        sigma_for_limits = sigma_xbar
    else:
        sigma_for_limits = stored_sigma

    # Step 3: Center line
    collector.step(
        label="X-bar (Center Line)",
        formula_latex=(
            r"\bar{x}" if subgroup_size == 1
            else r"\bar{\bar{x}}"
        ),
        substitution_latex=(
            r"\bar{x} = " + str(round(stored_center, 6))
            if subgroup_size == 1
            else r"\bar{\bar{x}} = " + str(round(stored_center, 6))
        ),
        result=stored_center,
        note="Stored from last limit calculation",
    )

    # Step 4: UCL and LCL from stored values
    computed_ucl = stored_center + 3 * sigma_for_limits
    computed_lcl = stored_center - 3 * sigma_for_limits

    ucl_formula = (
        r"UCL = \bar{x} + 3\sigma" if subgroup_size == 1
        else r"UCL = \bar{\bar{x}} + 3\sigma_{\bar{x}}"
    )
    lcl_formula = (
        r"LCL = \bar{x} - 3\sigma" if subgroup_size == 1
        else r"LCL = \bar{\bar{x}} - 3\sigma_{\bar{x}}"
    )

    collector.step(
        label="UCL (Upper Control Limit)",
        formula_latex=ucl_formula,
        substitution_latex=(
            r"UCL = "
            + str(round(stored_center, 6))
            + r" + 3 \times "
            + str(round(sigma_for_limits, 6))
        ),
        result=computed_ucl,
    )
    collector.step(
        label="LCL (Lower Control Limit)",
        formula_latex=lcl_formula,
        substitution_latex=(
            r"LCL = "
            + str(round(stored_center, 6))
            + r" - 3 \times "
            + str(round(sigma_for_limits, 6))
        ),
        result=computed_lcl,
    )

    # Use stored UCL/LCL as the authoritative displayed values.
    # These are set during recalculate-limits or manual entry and are what
    # the UI actually shows.  The computed values above are for the formula
    # steps only — if they differ from stored (e.g., manual limits or
    # rounding), the stored values take precedence.
    display_ucl = stored_ucl if stored_ucl is not None else computed_ucl
    display_lcl = stored_lcl if stored_lcl is not None else computed_lcl
    display_center = stored_center
    display_sigma = stored_sigma

    # If stored limits differ from formula-computed values, add a note
    # so the user understands why the displayed value doesn't match the math
    ucl_mismatch = stored_ucl is not None and abs(stored_ucl - computed_ucl) > 1e-6
    lcl_mismatch = stored_lcl is not None and abs(stored_lcl - computed_lcl) > 1e-6

    if ucl_mismatch:
        collector.step(
            label="UCL (Stored Override)",
            formula_latex=r"\text{UCL}_{\text{displayed}} = \text{stored value}",
            substitution_latex=(
                r"\text{UCL}_{\text{displayed}} = "
                + str(round(stored_ucl, 6))
                + r" \neq "
                + str(round(computed_ucl, 6))
            ),
            result=stored_ucl,
            note=(
                "The displayed UCL uses the stored value rather than the formula result. "
                "This occurs when limits were manually entered, imported, or calculated "
                "with different data than the current stored sigma. "
                "Recalculate limits to synchronize."
            ),
        )

    if lcl_mismatch:
        collector.step(
            label="LCL (Stored Override)",
            formula_latex=r"\text{LCL}_{\text{displayed}} = \text{stored value}",
            substitution_latex=(
                r"\text{LCL}_{\text{displayed}} = "
                + str(round(stored_lcl, 6))
                + r" \neq "
                + str(round(computed_lcl, 6))
            ),
            result=stored_lcl,
            note=(
                "The displayed LCL uses the stored value rather than the formula result. "
                "This occurs when limits were manually entered, imported, or calculated "
                "with different data than the current stored sigma. "
                "Recalculate limits to synchronize."
            ),
        )

    if short_run_mode == "deviation" and target_value is not None:
        display_ucl = display_ucl - target_value
        display_lcl = display_lcl - target_value
        display_center = stored_center - target_value
        collector.step(
            label="UCL (Deviation from Target)",
            formula_latex=r"UCL_{dev} = UCL - T",
            substitution_latex=(
                r"UCL_{dev} = "
                + str(round(computed_ucl, 6))
                + r" - "
                + str(round(target_value, 6))
            ),
            result=display_ucl,
            note=f"Short-run deviation mode: shift by target ({target_value})",
        )
        collector.step(
            label="LCL (Deviation from Target)",
            formula_latex=r"LCL_{dev} = LCL - T",
            substitution_latex=(
                r"LCL_{dev} = "
                + str(round(computed_lcl, 6))
                + r" - "
                + str(round(target_value, 6))
            ),
            result=display_lcl,
            note=f"Short-run deviation mode: shift by target ({target_value})",
        )

    elif short_run_mode == "standardized" and target_value is not None and stored_sigma:
        display_ucl = 3.0
        display_lcl = -3.0
        display_center = 0.0
        collector.step(
            label="UCL (Standardized Z-score)",
            formula_latex=r"UCL_Z = +3",
            substitution_latex=r"UCL_Z = +3",
            result=3.0,
            note="Short-run standardized mode: Z = (x̄ − T) / σ_x̄, limits are fixed ±3",
        )
        collector.step(
            label="LCL (Standardized Z-score)",
            formula_latex=r"LCL_Z = -3",
            substitution_latex=r"LCL_Z = -3",
            result=-3.0,
            note="Short-run standardized mode: Z = (x̄ − T) / σ_x̄, limits are fixed ±3",
        )

    # Map metric to displayed value
    metric_value_map = {
        "ucl": display_ucl,
        "lcl": display_lcl,
        "center_line": display_center,
        "sigma": display_sigma,
    }
    metric_value = metric_value_map[metric_type]

    display_name, formula_latex = CONTROL_LIMITS_DEFINITIONS[metric_type]

    # Filter steps to only those relevant to the requested metric
    prefixes = CONTROL_LIMITS_STEP_PREFIXES.get(metric_type, [])
    relevant_steps = [
        s
        for s in collector.steps
        if any(s.label.startswith(p) for p in prefixes)
    ]

    return ExplanationResponse(
        metric=metric_type,
        display_name=display_name,
        value=metric_value,
        formula_latex=formula_latex,
        steps=[
            ExplanationStepSchema(
                label=s.label,
                formula_latex=s.formula_latex,
                substitution_latex=s.substitution_latex,
                result=s.result,
                note=s.note,
            )
            for s in relevant_steps
        ],
        inputs=collector.inputs,
        citation=CitationSchema(
            standard=CONTROL_LIMITS_CITATION.standard,
            reference=CONTROL_LIMITS_CITATION.reference,
            section=CONTROL_LIMITS_CITATION.section,
        ),
        method=method,
        sigma_estimator=method,
        warnings=collector.warnings,
    )


# ---------------------------------------------------------------------------
# Attribute SPC explanation
# ---------------------------------------------------------------------------


@router.get(
    "/attribute/{metric_type}/{characteristic_id}",
    response_model=ExplanationResponse,
)
async def explain_attribute_metric(
    metric_type: str,
    characteristic_id: int,
    db: AsyncSession = Depends(get_db_session),
    current_user: User = Depends(get_current_user),
):
    """Return step-by-step explanation of an attribute SPC metric.

    Supports center_line, ucl, lcl for all attribute chart types (p, np, c, u),
    and sigma_z (Laney correction) for p and u charts.
    """
    if metric_type not in ATTRIBUTE_METRICS:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unknown attribute metric: {metric_type}",
        )

    # Plant RBAC check
    plant_id = await resolve_plant_id_for_characteristic(characteristic_id, db)
    check_plant_role(current_user, plant_id, "operator")

    # Load characteristic
    from sqlalchemy import select as sa_select

    from cassini.db.models.characteristic import Characteristic

    stmt = sa_select(Characteristic).where(Characteristic.id == characteristic_id)
    result = await db.execute(stmt)
    char = result.scalar_one_or_none()
    if char is None:
        raise HTTPException(status_code=404, detail="Characteristic not found")

    # Only attribute charts support this endpoint
    if char.data_type != "attribute":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="This endpoint only supports attribute charts",
        )

    chart_type = char.attribute_chart_type
    if not chart_type:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Characteristic has no attribute_chart_type configured",
        )

    # sigma_z only applies to p and u charts
    if metric_type == "sigma_z" and chart_type not in ("p", "u"):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Laney sigma_z correction only applies to p and u charts",
        )

    # Load attribute samples
    repo = SampleRepository(db)
    samples = await repo.get_by_characteristic(char_id=characteristic_id)

    # Filter excluded and reshape to dicts
    sample_dicts: list[dict] = []
    for s in samples:
        if s.is_excluded:
            continue
        d: dict = {"defect_count": s.defect_count}
        if s.sample_size is not None:
            d["sample_size"] = s.sample_size
        if s.units_inspected is not None:
            d["units_inspected"] = s.units_inspected
        sample_dicts.append(d)

    if len(sample_dicts) < 2:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Need at least 2 non-excluded attribute samples",
        )

    # Run attribute limit calculation with collector
    collector = ExplanationCollector()
    try:
        limits = calculate_attribute_limits(chart_type, sample_dicts, collector=collector)
    except ValueError:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Cannot compute attribute limits for this configuration",
        )

    # For sigma_z, run Laney calculation as well
    sigma_z_value: float | None = None
    if metric_type == "sigma_z":
        if len(sample_dicts) < 3:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Need at least 3 samples for Laney sigma_z calculation",
            )
        sigma_z_value = calculate_laney_sigma_z(
            chart_type, sample_dicts, limits.center_line, collector=collector,
        )

    # Map metric to value
    metric_value_map: dict[str, float] = {
        "center_line": limits.center_line,
        "ucl": limits.ucl,
        "lcl": limits.lcl,
    }
    if sigma_z_value is not None:
        metric_value_map["sigma_z"] = sigma_z_value

    metric_value = metric_value_map.get(metric_type)
    if metric_value is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Cannot compute {metric_type} for this characteristic",
        )

    display_name, formula_latex = ATTRIBUTE_METRIC_DEFINITIONS[metric_type]

    # Filter steps to only those relevant to the requested metric
    prefixes = ATTRIBUTE_STEP_PREFIXES.get(metric_type, [])
    relevant_steps = [
        s
        for s in collector.steps
        if any(s.label.startswith(p) for p in prefixes)
    ]

    return ExplanationResponse(
        metric=metric_type,
        display_name=display_name,
        value=metric_value,
        formula_latex=formula_latex,
        steps=[
            ExplanationStepSchema(
                label=s.label,
                formula_latex=s.formula_latex,
                substitution_latex=s.substitution_latex,
                result=s.result,
                note=s.note,
            )
            for s in relevant_steps
        ],
        inputs=collector.inputs,
        citation=CitationSchema(
            standard=ATTRIBUTE_SPC_CITATION.standard,
            reference=ATTRIBUTE_SPC_CITATION.reference,
            section=ATTRIBUTE_SPC_CITATION.section,
        ),
        method=chart_type,
        warnings=collector.warnings,
    )


# ---------------------------------------------------------------------------
# MSA (Measurement System Analysis) explanation
# ---------------------------------------------------------------------------

MSA_METRIC_DEFINITIONS: dict[str, tuple[str, str]] = {
    "pct_study_grr": (
        "%Study GRR",
        r"\%\text{Study GRR} = \frac{\text{GRR}}{\text{TV}} \times 100",
    ),
    "pct_study_ev": (
        "%Study EV",
        r"\%\text{Study EV} = \frac{\text{EV}}{\text{TV}} \times 100",
    ),
    "pct_study_av": (
        "%Study AV",
        r"\%\text{Study AV} = \frac{\text{AV}}{\text{TV}} \times 100",
    ),
    "ndc": (
        "Number of Distinct Categories",
        r"\text{ndc} = \lfloor 1.41 \times \frac{\text{PV}}{\text{GRR}} \rfloor",
    ),
    "pct_tolerance_grr": (
        "%Tolerance GRR",
        r"\%\text{Tol GRR} = \frac{5.15 \times \text{GRR}}{\text{USL} - \text{LSL}} \times 100",
    ),
    "f_operator": (
        "F-statistic (Operator)",
        r"F_{\text{operator}} = \frac{MS_{\text{operator}}}{MS_{\text{interaction}}}",
    ),
    "f_part": (
        "F-statistic (Part)",
        r"F_{\text{part}} = \frac{MS_{\text{part}}}{MS_{\text{interaction}}}",
    ),
    "f_interaction": (
        "F-statistic (Interaction)",
        r"F_{\text{interaction}} = \frac{MS_{\text{interaction}}}{MS_{\text{equipment}}}",
    ),
    "fleiss_kappa": (
        "Fleiss' Kappa",
        r"\kappa = \frac{\bar{P} - P_e}{1 - P_e}",
    ),
    "cohens_kappa": (
        "Cohen's Kappa",
        r"\kappa = \frac{p_o - p_e}{1 - p_e}",
    ),
    "between_appraiser": (
        "Between-Appraiser Agreement",
        r"\%\text{between} = \frac{\text{parts where all operators agree}}{n_p} \times 100",
    ),
}

MSA_METRIC_STEP_PREFIXES: dict[str, list[str]] = {
    "pct_study_grr": [
        "Grand", "SS", "MS", "F-", "Variance", "\u03c3\u00b2",
        "EV", "AV", "GRR", "PV", "TV", "%Study GRR",
        "R-bar", "d2", "K1", "K3", "Operator range", "Part range",
    ],
    "pct_study_ev": [
        "Grand", "SS", "MS", "Variance", "\u03c3\u00b2",
        "EV", "TV", "%Study EV",
        "R-bar", "d2",
    ],
    "pct_study_av": [
        "Grand", "SS", "MS", "Variance", "\u03c3\u00b2",
        "AV", "TV", "%Study AV",
        "K1", "Operator range",
    ],
    "ndc": ["GRR", "PV", "TV", "ndc", "EV", "AV"],
    "pct_tolerance_grr": ["GRR", "EV", "AV", "TV", "%Tolerance"],
    "f_operator": ["SS", "MS", "F-stat (Operator)"],
    "f_part": ["SS", "MS", "F-stat (Part)"],
    "f_interaction": ["SS", "MS", "F-stat (Interaction)"],
    "fleiss_kappa": ["Between", "Fleiss", "P\u0304", "P_e"],
    "cohens_kappa": ["Cohen", "p_o", "p_e"],
    "between_appraiser": ["Between-appraiser"],
}

# Variable metrics require study_type in (crossed_anova, range_method, nested_anova)
MSA_VARIABLE_METRICS = {
    "pct_study_grr", "pct_study_ev", "pct_study_av", "ndc",
    "pct_tolerance_grr", "f_operator", "f_part", "f_interaction",
}
# F-statistics are only available for crossed ANOVA
MSA_F_STAT_METRICS = {"f_operator", "f_part", "f_interaction"}
# Attribute metrics require study_type == "attribute_agreement"
MSA_ATTRIBUTE_METRICS = {"fleiss_kappa", "cohens_kappa", "between_appraiser"}


@router.get(
    "/msa/{metric_type}/{study_id}",
    response_model=ExplanationResponse,
)
async def explain_msa_metric(
    metric_type: str,
    study_id: int,
    db: AsyncSession = Depends(get_db_session),
    current_user: User = Depends(get_current_user),
):
    """Return step-by-step explanation of an MSA metric.

    Supports variable Gage R&R metrics (%Study, ndc, F-statistics) and
    attribute Kappa metrics (Cohen's, Fleiss').
    """
    if metric_type not in MSA_METRIC_DEFINITIONS:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unknown MSA metric: {metric_type}",
        )

    # Load study with operators and parts
    stmt = (
        select(MSAStudy)
        .where(MSAStudy.id == study_id)
        .options(
            selectinload(MSAStudy.operators),
            selectinload(MSAStudy.parts),
        )
    )
    result = await db.execute(stmt)
    study = result.scalar_one_or_none()
    if study is None:
        raise HTTPException(status_code=404, detail="MSA study not found")

    # RBAC check
    check_plant_role(current_user, study.plant_id, "operator")

    # Determine study category
    is_variable = study.study_type in ("crossed_anova", "range_method", "nested_anova")
    is_attribute = study.study_type == "attribute_agreement"

    # Validate metric vs study type
    if metric_type in MSA_VARIABLE_METRICS and not is_variable:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Metric '{metric_type}' requires a variable MSA study (crossed_anova/range_method/nested_anova)",
        )
    if metric_type in MSA_ATTRIBUTE_METRICS and not is_attribute:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Metric '{metric_type}' requires an attribute MSA study",
        )
    if metric_type in MSA_F_STAT_METRICS and study.study_type != "crossed_anova":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"F-statistic metrics are only available for crossed ANOVA studies",
        )

    # Load measurements
    meas_result = await db.execute(
        select(MSAMeasurement).where(MSAMeasurement.study_id == study_id)
    )
    measurements = list(meas_result.scalars().all())

    if not measurements:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="No measurements found for this study",
        )

    # Build operator/part index maps by sequence_order
    sorted_operators = sorted(study.operators, key=lambda o: o.sequence_order)
    sorted_parts = sorted(study.parts, key=lambda p: p.sequence_order)
    op_index = {op.id: i for i, op in enumerate(sorted_operators)}
    part_index = {p.id: i for i, p in enumerate(sorted_parts)}

    n_ops = len(sorted_operators)
    n_parts = len(sorted_parts)
    n_reps = study.num_replicates

    collector = ExplanationCollector()

    if is_variable:
        # Reshape to 3D: [operators][parts][replicates] -> float
        data_3d: list[list[list[float | None]]] = [
            [[None] * n_reps for _ in range(n_parts)]
            for _ in range(n_ops)
        ]
        for m in measurements:
            oi = op_index.get(m.operator_id)
            pi = part_index.get(m.part_id)
            if oi is None or pi is None:
                continue
            ri = m.replicate_num - 1
            if 0 <= ri < n_reps:
                data_3d[oi][pi][ri] = m.value

        # Validate completeness
        for i in range(n_ops):
            for j in range(n_parts):
                for k in range(n_reps):
                    if data_3d[i][j][k] is None:
                        raise HTTPException(
                            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                            detail="Measurement matrix is incomplete",
                        )

        # Compute tolerance from linked characteristic if study has one
        tolerance = study.tolerance
        if tolerance is None and study.characteristic_id is not None:
            from cassini.db.models.characteristic import Characteristic

            char_stmt = select(Characteristic).where(
                Characteristic.id == study.characteristic_id
            )
            char_result = await db.execute(char_stmt)
            char = char_result.scalar_one_or_none()
            if char is not None and char.usl is not None and char.lsl is not None:
                tolerance = char.usl - char.lsl

        # Run appropriate engine method with collector
        engine = GageRREngine()
        try:
            if study.study_type == "crossed_anova":
                grr_result = engine.calculate_crossed_anova(
                    data_3d, tolerance, collector=collector,  # type: ignore[arg-type]
                )
            elif study.study_type == "range_method":
                grr_result = engine.calculate_range_method(
                    data_3d, tolerance, collector=collector,  # type: ignore[arg-type]
                )
            else:  # nested_anova
                grr_result = engine.calculate_nested_anova(
                    data_3d, tolerance, collector=collector,  # type: ignore[arg-type]
                )
        except ValueError:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Insufficient data for MSA calculation",
            )

        # Extract metric value from result
        metric_value_map = {
            "pct_study_grr": grr_result.pct_study_grr,
            "pct_study_ev": grr_result.pct_study_ev,
            "pct_study_av": grr_result.pct_study_av,
            "ndc": float(grr_result.ndc),
            "pct_tolerance_grr": grr_result.pct_tolerance_grr,
            "f_operator": grr_result.anova_table["operator"]["F"] if grr_result.anova_table else None,
            "f_part": grr_result.anova_table["part"]["F"] if grr_result.anova_table else None,
            "f_interaction": grr_result.anova_table["interaction"]["F"] if grr_result.anova_table else None,
        }
        metric_value = metric_value_map.get(metric_type)
        if metric_value is None:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Cannot compute {metric_type} for this study",
            )

        citation = MSA_CITATION

    else:
        # Attribute study
        attr_3d: list[list[list[str | None]]] = [
            [[None] * n_reps for _ in range(n_parts)]
            for _ in range(n_ops)
        ]
        for m in measurements:
            oi = op_index.get(m.operator_id)
            pi = part_index.get(m.part_id)
            if oi is None or pi is None:
                continue
            ri = m.replicate_num - 1
            if 0 <= ri < n_reps:
                attr_3d[oi][pi][ri] = m.attribute_value

        # Validate completeness
        for i in range(n_ops):
            for j in range(n_parts):
                for k in range(n_reps):
                    if attr_3d[i][j][k] is None:
                        raise HTTPException(
                            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                            detail="Attribute measurement matrix is incomplete",
                        )

        operator_names = [op.name for op in sorted_operators]

        attr_engine = AttributeMSAEngine()
        try:
            attr_result = attr_engine.calculate(
                attr_3d,  # type: ignore[arg-type]
                operator_names=operator_names,
                collector=collector,
            )
        except ValueError:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Insufficient data for attribute MSA calculation",
            )

        # Extract metric value
        if metric_type == "fleiss_kappa":
            metric_value = attr_result.fleiss_kappa
        elif metric_type == "between_appraiser":
            metric_value = attr_result.between_appraiser
        elif metric_type == "cohens_kappa":
            # Return the first pairwise kappa (or average if preferred)
            if attr_result.cohens_kappa_pairs:
                # Use average of all pairwise kappas
                kappa_values = list(attr_result.cohens_kappa_pairs.values())
                metric_value = sum(kappa_values) / len(kappa_values)
            else:
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail="No pairwise Cohen's Kappa values available",
                )
        else:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail=f"Cannot compute {metric_type} for this study",
            )

        citation = ATTRIBUTE_MSA_CITATION

    display_name, formula_latex = MSA_METRIC_DEFINITIONS[metric_type]

    # Filter steps by prefix
    prefixes = MSA_METRIC_STEP_PREFIXES.get(metric_type, [])
    relevant_steps = [
        s
        for s in collector.steps
        if any(s.label.startswith(p) for p in prefixes)
    ]

    return ExplanationResponse(
        metric=metric_type,
        display_name=display_name,
        value=metric_value,
        formula_latex=formula_latex,
        steps=[
            ExplanationStepSchema(
                label=s.label,
                formula_latex=s.formula_latex,
                substitution_latex=s.substitution_latex,
                result=s.result,
                note=s.note,
            )
            for s in relevant_steps
        ],
        inputs=collector.inputs,
        citation=CitationSchema(
            standard=citation.standard,
            reference=citation.reference,
            section=citation.section,
        ),
        method=study.study_type,
        warnings=collector.warnings,
    )
