"""Show Your Work — Explain API.

Returns step-by-step formula breakdowns for statistical metrics,
generated by the same engine code that computed the values.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from cassini.api.deps import (
    check_plant_role,
    get_current_user,
    get_db_session,
    resolve_plant_id_for_characteristic,
)
from cassini.api.schemas.explain import CitationSchema, ExplanationResponse, ExplanationStepSchema
from cassini.core.capability import calculate_capability
from cassini.core.explain import (
    CAPABILITY_CITATION,
    ExplanationCollector,
)
from cassini.db.models.user import User
from cassini.db.repositories.sample import SampleRepository

router = APIRouter(prefix="/api/v1/explain", tags=["explain"])

# Metric type -> display name + general formula
METRIC_DEFINITIONS = {
    "cp": ("Process Potential (Cp)", r"C_p = \frac{USL - LSL}{6\sigma_w}"),
    "cpk": (
        "Process Capability (Cpk)",
        r"C_{pk} = \min\left(\frac{USL - \bar{x}}{3\sigma_w}, \frac{\bar{x} - LSL}{3\sigma_w}\right)",
    ),
    "pp": ("Process Performance (Pp)", r"P_p = \frac{USL - LSL}{6\sigma_{overall}}"),
    "ppk": (
        "Process Performance (Ppk)",
        r"P_{pk} = \min\left(\frac{USL - \bar{x}}{3\sigma_{overall}}, \frac{\bar{x} - LSL}{3\sigma_{overall}}\right)",
    ),
    "cpm": (
        "Taguchi Capability (Cpm)",
        r"C_{pm} = \frac{USL - LSL}{6\tau}, \quad \tau = \sqrt{\sigma_w^2 + (\bar{x} - T)^2}",
    ),
}

CAPABILITY_METRICS = {"cp", "cpk", "pp", "ppk", "cpm"}


@router.get(
    "/capability/{metric_type}/{characteristic_id}",
    response_model=ExplanationResponse,
)
async def explain_capability_metric(
    metric_type: str,
    characteristic_id: int,
    db: AsyncSession = Depends(get_db_session),
    current_user: User = Depends(get_current_user),
):
    """Return step-by-step explanation of a capability metric."""
    if metric_type not in CAPABILITY_METRICS:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Unknown capability metric: {metric_type}",
        )

    # Plant RBAC check (resolve plant_id through hierarchy)
    plant_id = await resolve_plant_id_for_characteristic(characteristic_id, db)
    check_plant_role(current_user, plant_id, "operator")

    # Load characteristic
    from sqlalchemy import select as sa_select

    from cassini.db.models.characteristic import Characteristic

    stmt = sa_select(Characteristic).where(Characteristic.id == characteristic_id)
    result = await db.execute(stmt)
    char = result.scalar_one_or_none()
    if char is None:
        raise HTTPException(status_code=404, detail="Characteristic not found")

    # Only variable charts support capability explanation
    if char.data_type == "attribute":
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Capability analysis is not supported for attribute charts",
        )

    if char.usl is None and char.lsl is None:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="At least one specification limit (USL or LSL) must be set",
        )

    # Fetch sample values (same path as capability endpoint)
    repo = SampleRepository(db)
    sample_data = await repo.get_rolling_window_data(
        char_id=characteristic_id,
        window_size=1000,
        exclude_excluded=True,
    )

    # Flatten all individual measurements
    values: list[float] = []
    for sd in sample_data:
        values.extend(sd["values"])

    if len(values) < 2:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Need at least 2 measurements",
        )

    # Run capability with collector
    collector = ExplanationCollector()
    cap_result = calculate_capability(
        values=values,
        usl=char.usl,
        lsl=char.lsl,
        target=char.target_value,
        sigma_within=char.stored_sigma,
        collector=collector,
    )

    # Extract the requested metric value
    metric_value = getattr(cap_result, metric_type, None)
    if metric_value is None:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Cannot compute {metric_type} -- check specification limits and data",
        )

    display_name, formula_latex = METRIC_DEFINITIONS[metric_type]

    return ExplanationResponse(
        metric=metric_type,
        display_name=display_name,
        value=metric_value,
        formula_latex=formula_latex,
        steps=[
            ExplanationStepSchema(
                label=s.label,
                formula_latex=s.formula_latex,
                substitution_latex=s.substitution_latex,
                result=s.result,
                note=s.note,
            )
            for s in collector.steps
        ],
        inputs=collector.inputs,
        citation=CitationSchema(
            standard=CAPABILITY_CITATION.standard,
            reference=CAPABILITY_CITATION.reference,
            section=CAPABILITY_CITATION.section,
        ),
        method="normal",
        warnings=collector.warnings,
    )
