/**
 * Read the E2E seed manifest generated by backend/scripts/seed_e2e.py.
 * Contains all entity IDs created during global-setup so specs can
 * reference pre-seeded data without creating it via API.
 */
import fs from 'fs'
import path from 'path'

const MANIFEST_PATH = path.resolve(process.cwd(), '../backend/e2e-manifest.json')

export interface SeedManifest {
  admin_user_id: number
  // Standard hierarchy plants (seedFullHierarchy pattern)
  dashboard: StandardHierarchy
  annotations: StandardHierarchy
  data_entry: StandardHierarchy
  violations: StandardHierarchy
  reports: StandardHierarchy
  sample_mgmt: StandardHierarchy
  config: StandardHierarchy
  inspector: StandardHierarchy
  csv_import: StandardHierarchy
  rbac: StandardHierarchy
  // Kiosk (2 characteristics)
  kiosk: StandardHierarchy & { char_id_2: number }
  // CUSUM/EWMA
  cusum_ewma: {
    plant_id: number
    station_id: number
    cusum_char_id: number
    ewma_char_id: number
  }
  // Attribute charts
  attribute_charts: {
    plant_id: number
    station_id: number
    p_char_id: number
    np_char_id: number
    c_char_id: number
    u_char_id: number
  }
  // Product limits
  product_limits: StandardHierarchy
  // Simple plants
  connectivity: { plant_id: number }
  navigation: { plant_id: number }
  hierarchy: { plant_id: number }
  mobile: { plant_id: number }
  users: { plant_id: number }
  settings: { plant_id: number }
  // Notifications
  notifications: { webhook_id: number }
  // Screenshot tour (commercial feature data)
  screenshot_tour: StandardHierarchy & {
    msa_study_id: number
    fai_report_id: number
    doe_study_id: number
    broker_id: number
    workflow_id: number
  }
}

export interface StandardHierarchy {
  plant_id: number
  dept_id: number
  line_id: number
  station_id: number
  char_id: number
}

let _cached: SeedManifest | null = null

export function getManifest(): SeedManifest {
  if (_cached) return _cached
  if (!fs.existsSync(MANIFEST_PATH)) {
    throw new Error(
      `E2E manifest not found at ${MANIFEST_PATH}. ` +
        'Run playwright with globalSetup or run: python backend/scripts/seed_e2e.py',
    )
  }
  _cached = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf-8'))
  return _cached!
}
