"""Non-normal distribution fitting and capability analysis.

PURPOSE:
    Provides three methods for computing process capability indices when the
    data does not follow a normal distribution. Non-normal data is common in
    manufacturing (e.g., tool wear produces right-skewed distributions,
    surface roughness follows lognormal, fatigue life follows Weibull).
    Standard Cp/Cpk formulas assume normality and produce misleading results
    on non-normal data.

STANDARDS:
    - Box, G.E.P. & Cox, D.R. (1964), "An Analysis of Transformations",
      JRSS Series B, 26(2), pp.211-252 -- Box-Cox power transformation
    - ISO 21747:2006, "Statistical methods -- Process performance and
      capability statistics for measured quality characteristics",
      Section 7: Percentile method for non-normal capability
    - ASTM E2587-16, Section 10: Non-normal data and transformations
    - Montgomery (2019), "Introduction to Statistical Quality Control",
      8th Ed., Chapter 7, Section 7.5: Process Capability Analysis with
      Non-Normal Data
    - Burnham, K.P. & Anderson, D.R. (2002), "Model Selection and
      Multimodel Inference", Springer -- AICc as selection criterion
    - D'Agostino, R.B. & Stephens, M.A. (1986), "Goodness-of-Fit
      Techniques", Marcel Dekker -- Anderson-Darling and KS tests
    - Lilliefors, H.W. (1967), "On the Kolmogorov-Smirnov test for
      normality with mean and variance unknown", JASA 62(318), pp.399-402
    - Johnson, N.L. (1949), "Systems of frequency curves generated by
      methods of translation", Biometrika, 36, pp.149-176 -- Johnson
      distribution families

ARCHITECTURE:
    Three non-normal capability methods, applied in cascade:
      1. Box-Cox transformation: Transform data to approximate normality,
         then apply standard Cp/Cpk formulas in the transformed space.
         Spec limits are also transformed. Within-subgroup sigma is
         transformed via the delta method.
      2. Percentile method (ISO 21747): Use P0.135, P50, P99.865 percentiles
         (the normal-equivalent 3-sigma points) to estimate process spread
         without distributional assumptions.
      3. Distribution fitting: Fit multiple parametric families (normal,
         lognormal, Weibull, gamma, Johnson SU/SB) via MLE, rank by AICc,
         and compute capability from the best-fitting distribution's
         percentiles.

    The "auto" method cascades: try Box-Cox first; if it fails (e.g.,
    non-positive data), fall back to distribution fitting; always compute
    percentile method as a robust fallback.

KEY DECISIONS:
    - Model selection uses AICc (corrected Akaike Information Criterion),
      not goodness-of-fit p-values, as the PRIMARY ranking criterion.
      AICc balances fit quality against model complexity and is valid
      regardless of parameter estimation method.
      Ref: Burnham & Anderson (2002), Chapter 2.
    - GoF tests (Anderson-Darling for normal, KS for others) serve as
      ADVISORY absolute rejection filters only. The KS test with estimated
      parameters (Lilliefors effect) has inflated Type I error, making its
      p-values optimistically biased. See _anderson_darling_test docstring.
    - Box-Cox within-sigma transformation uses the delta method:
      sigma_t = sigma * |x-bar^(lambda-1)|. This is adequate when
      CV < ~30%. For the original-scale mean, we use np.mean(original_values)
      to avoid Jensen's inequality bias from back-transformation.
    - Q-Q plots use Blom plotting positions p_i = (i - 3/8) / (n + 1/4),
      which are recommended for probability plots across distribution
      families.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import math
from typing import TYPE_CHECKING, Optional

import numpy as np
from scipy import stats as scipy_stats
from scipy.stats import boxcox

if TYPE_CHECKING:
    from cassini.core.explain import ExplanationCollector


@dataclass
class HistogramData:
    """Pre-computed histogram bin data from actual measurements."""

    bin_edges: list[float]  # n+1 edges
    counts: list[int]  # n bin counts
    density: list[float]  # n density values (count / (N * bin_width))


@dataclass
class DistributionFitResult:
    """Result of fitting a single distribution family."""

    family: str  # "normal", "lognormal", "weibull", "gamma", "johnson_su", "johnson_sb"
    parameters: dict[str, float]  # Family-specific params
    ad_statistic: float  # Goodness-of-fit test statistic
    ad_p_value: float | None  # p-value (None if not available)
    aic: float  # Akaike Information Criterion (lower = better)
    is_adequate_fit: bool  # True if p-value >= 0.05 or stat below critical.
    # ADVISORY ONLY for non-normal dists — see _anderson_darling_test docstring
    # for Lilliefors effect. Model selection uses AICc ranking, not this flag.
    gof_test_type: str = "anderson_darling"  # "anderson_darling" or "kolmogorov_smirnov"


@dataclass
class NonNormalCapabilityResult:
    """Result of non-normal process capability calculation."""

    cp: float | None
    cpk: float | None
    pp: float | None
    ppk: float | None
    cpm: float | None
    method: str  # "normal", "box_cox", "percentile", "distribution_fit", "auto"
    method_detail: str  # Human-readable: "Box-Cox (lambda=0.32)" or "Weibull (shape=1.5)"
    normality_p_value: float | None
    normality_test: str
    is_normal: bool
    fitted_distribution: DistributionFitResult | None
    percentile_pp: float | None
    percentile_ppk: float | None
    p0_135: float | None
    p50: float | None
    p99_865: float | None
    sample_count: int
    calculated_at: datetime
    histogram: HistogramData | None = None
    qq_points: dict[str, list[float]] | None = None


def _round_or_none(value: float | None, decimals: int = 4) -> float | None:
    """Round a value to the specified decimals, or return None."""
    if value is None:
        return None
    if not math.isfinite(value):
        return None
    return round(value, decimals)


def _compute_aic(n: int, k: int, log_likelihood: float) -> float:
    """Compute corrected Akaike Information Criterion (AICc).

    Formula:
        AIC  = 2k - 2*ln(L)
        AICc = AIC + 2k(k+1) / (n-k-1)

    where k = number of estimated parameters, n = sample size,
    L = maximized likelihood.

    The finite-sample correction term (Hurvich & Tsai, 1989) penalizes
    complex models (e.g., 4-parameter Johnson) relative to simpler ones
    (e.g., 2-parameter normal) when sample size is small. Without this
    correction, AIC tends to select overly complex models for n < ~40.

    Ref: Burnham, K.P. & Anderson, D.R. (2002), "Model Selection and
         Multimodel Inference", Springer, Chapter 2, Eq. (2.1)-(2.4).
         Hurvich, C.M. & Tsai, C.-L. (1989), "Regression and time series
         model selection in small samples", Biometrika, 76, pp.297-307.
    """
    aic = 2 * k - 2 * log_likelihood
    if n > k + 1:
        aic += 2 * k * (k + 1) / (n - k - 1)
    return aic


def _log_likelihood(dist, params, data: np.ndarray) -> float:
    """Compute log-likelihood for a fitted distribution."""
    try:
        ll = np.sum(dist.logpdf(data, *params))
        if not math.isfinite(ll):
            return -1e18
        return float(ll)
    except Exception:
        return -1e18


def _anderson_darling_test(
    dist, params, data: np.ndarray
) -> tuple[float, float | None, bool, str]:
    """Run goodness-of-fit test.

    Returns (statistic, p_value, is_adequate_fit, test_type).

    For normal distribution: uses Anderson-Darling with proper p-value.
    For other distributions: uses Kolmogorov-Smirnov (clearly labeled).

    IMPORTANT — KS with estimated parameters (Lilliefors effect):
    ---------------------------------------------------------------
    When distribution parameters (shape, scale, location) are estimated
    from the SAME data used for the goodness-of-fit test, the standard
    KS critical values are invalid. Lilliefors (1967) demonstrated that
    the true critical values are substantially higher (i.e., the standard
    KS test is liberal — it accepts fits too easily).

    For normality testing, Lilliefors correction tables exist. For other
    distribution families (Weibull, Gamma, Lognormal, Johnson), no
    standard correction tables are available. Parametric bootstrap could
    provide exact p-values but is computationally expensive.

    CONSEQUENCE FOR MODEL SELECTION:
    The ``is_adequate_fit`` flag returned here is ADVISORY ONLY when used
    with non-normal distributions whose parameters were estimated from
    the same data. It serves as an absolute rejection filter (a very
    poor fit will still fail), but should NOT be the primary criterion
    for selecting among candidate distributions.

    The primary model selection criterion is AICc (corrected Akaike
    Information Criterion), computed in ``_compute_aic()`` and used for
    ranking in ``DistributionFitter.fit_all()``. AICc balances goodness-
    of-fit against model complexity and is valid regardless of whether
    parameters were estimated from the data.

    References:
        - Lilliefors, H.W. (1967). "On the Kolmogorov-Smirnov test for
          normality with mean and variance unknown." JASA, 62(318), 399-402.
        - Burnham, K.P. & Anderson, D.R. (2002). "Model Selection and
          Multimodel Inference." Springer. — AICc as preferred criterion.
        - D'Agostino, R.B. & Stephens, M.A. (1986). "Goodness-of-Fit
          Techniques." Marcel Dekker. — comprehensive GoF test reference.
        - ASTM E2587-16. "Standard Practice for Use of Control Charts in
          Statistical Process Control" — non-normal capability approach.
    """
    try:
        if dist == scipy_stats.norm:
            try:
                # scipy >= 1.17: use method parameter for proper p-value
                from scipy.stats import MonteCarloMethod  # noqa: F401
                result = scipy_stats.anderson(data, dist="norm", method="interpolate")
                ad_stat = float(result.statistic)
                p_value = float(result.pvalue) if hasattr(result, 'pvalue') else None
                is_adequate = p_value >= 0.05 if p_value is not None else ad_stat < 0.787
                return ad_stat, p_value, is_adequate, "anderson_darling"
            except (ImportError, TypeError):
                # scipy < 1.17: interpolate between critical values
                result = scipy_stats.anderson(data, dist="norm")
                ad_stat = float(result.statistic)
                # sig_levels = [15, 10, 5, 2.5, 1] (descending significance)
                # crit_vals = ascending (larger stat → smaller p-value)
                sig_levels = list(result.significance_level)
                crit_vals = list(result.critical_values)
                critical_5pct = crit_vals[2] if len(crit_vals) > 2 else crit_vals[-1]

                if ad_stat < crit_vals[0]:
                    # Below all critical values → very good fit, p > 0.15
                    # Extrapolate: scale by ratio of critical value to stat
                    p_value = min(1.0, (sig_levels[0] / 100.0) * (crit_vals[0] / max(ad_stat, 1e-10)))
                    p_value = min(p_value, 0.9999)
                elif ad_stat > crit_vals[-1]:
                    # Above all critical values → poor fit
                    p_value = 0.001
                else:
                    # Interpolate between bracketing significance levels
                    p_value = sig_levels[-1] / 100.0
                    for i in range(len(sig_levels) - 1):
                        if crit_vals[i] <= ad_stat <= crit_vals[i + 1]:
                            frac = (ad_stat - crit_vals[i]) / (crit_vals[i + 1] - crit_vals[i])
                            p_hi = sig_levels[i] / 100.0
                            p_lo = sig_levels[i + 1] / 100.0
                            p_value = p_hi - frac * (p_hi - p_lo)
                            break

                is_adequate = ad_stat < critical_5pct
                return ad_stat, p_value, is_adequate, "anderson_darling"

        # For non-normal distributions: KS test (clearly labeled as such).
        #
        # ADVISORY ONLY — see docstring for Lilliefors effect discussion.
        # The p-value here is optimistically biased because params were
        # estimated from `data`. The `is_adequate_fit` flag (p >= 0.05)
        # serves as a coarse sanity check / absolute rejection filter.
        # Model SELECTION among candidates uses AICc ranking, not this
        # p-value. See DistributionFitter.fit_all() sort at the end.
        #
        # Ref: Lilliefors (1967); Burnham & Anderson (2002) for AICc.
        ks_stat, ks_p = scipy_stats.kstest(data, dist.cdf, args=params)
        return float(ks_stat), float(ks_p), ks_p >= 0.05, "kolmogorov_smirnov"

    except Exception:
        return 999.0, None, False, "unknown"


class DistributionFitter:
    """Fits data to multiple distribution families and ranks them.

    Model Selection Strategy (ASTM E2587, Burnham & Anderson 2002):
    ----------------------------------------------------------------
    1. PRIMARY criterion: AICc (corrected Akaike Information Criterion).
       Results are sorted by AICc ascending — lowest AICc = best balance
       of goodness-of-fit vs. model complexity. AICc is valid even when
       parameters are estimated from the same data used for evaluation.

    2. SECONDARY criterion: Goodness-of-fit test (``is_adequate_fit``).
       For normal: Anderson-Darling with proper critical values.
       For non-normal: Kolmogorov-Smirnov (ADVISORY ONLY — see
       ``_anderson_darling_test`` docstring for Lilliefors effect).
       The GoF flag serves as an absolute rejection filter (catch
       egregiously poor fits) but does NOT drive selection ranking.

    Callers should use ``best_fit()`` or take ``fit_all()[0]`` for the
    AICc-optimal model. The ``is_adequate_fit`` flag can optionally be
    checked to warn the user if no candidate passes the GoF filter,
    but the AICc-ranked order remains the authoritative ranking.
    """

    # Distribution families to try: (name, scipy_dist, min_params)
    FAMILIES = [
        ("normal", scipy_stats.norm, 2),
        ("lognormal", scipy_stats.lognorm, 3),
        ("weibull", scipy_stats.weibull_min, 3),
        ("gamma", scipy_stats.gamma, 3),
        ("johnson_su", scipy_stats.johnsonsu, 4),
        ("johnson_sb", scipy_stats.johnsonsb, 4),
    ]

    # Families that require strictly positive data
    POSITIVE_ONLY = {"lognormal", "weibull", "gamma"}

    @staticmethod
    def fit_all(values: np.ndarray) -> list[DistributionFitResult]:
        """Fit data to all candidate distribution families.

        Each family is fitted via MLE, then evaluated with both AICc
        (for ranking) and a GoF test (for advisory adequacy flagging).

        Args:
            values: 1D array of measurement values. Requires n >= 8.

        Returns:
            List of DistributionFitResult sorted by AICc (best first).
            The GoF ``is_adequate_fit`` flag is informational — ranking
            is by AICc per Burnham & Anderson (2002). See class docstring.
        """
        if len(values) < 8:
            return []

        has_nonpositive = np.any(values <= 0)
        results: list[DistributionFitResult] = []

        for name, dist, n_params in DistributionFitter.FAMILIES:
            # Skip positive-only families if data has non-positive values
            if name in DistributionFitter.POSITIVE_ONLY and has_nonpositive:
                continue

            try:
                # MLE fit
                params = dist.fit(values)

                # Goodness-of-fit test
                gof_stat, gof_p, is_adequate, test_type = _anderson_darling_test(
                    dist, params, values
                )

                # Log-likelihood and AIC (AICc corrected)
                ll = _log_likelihood(dist, params, values)
                aic = _compute_aic(len(values), n_params, ll)

                # Build parameter dict
                param_dict = _params_to_dict(name, params)

                results.append(
                    DistributionFitResult(
                        family=name,
                        parameters=param_dict,
                        ad_statistic=round(gof_stat, 6),
                        ad_p_value=_round_or_none(gof_p, 6),
                        aic=round(aic, 2),
                        is_adequate_fit=is_adequate,
                        gof_test_type=test_type,
                    )
                )
            except Exception:
                continue

        # PRIMARY selection criterion: sort by AICc (lower = better fit
        # relative to model complexity). This is the authoritative ranking.
        # The GoF `is_adequate_fit` flag is secondary / advisory only —
        # see class docstring and _anderson_darling_test docstring for
        # the Lilliefors effect discussion on KS with estimated parameters.
        # Ref: Burnham & Anderson (2002), "Model Selection and Multimodel
        # Inference", Ch. 2 — AICc as the preferred selection criterion.
        results.sort(key=lambda r: r.aic)
        return results

    @staticmethod
    def fit_box_cox(values: np.ndarray) -> tuple[np.ndarray, float] | None:
        """Apply Box-Cox transformation.

        Args:
            values: 1D array of measurement values. All must be > 0.

        Returns:
            Tuple of (transformed_values, lambda) or None if not applicable.
        """
        if np.any(values <= 0):
            return None

        try:
            transformed, lmbda = boxcox(values)
            lmbda = float(lmbda)

            # Reject extreme lambda values
            if abs(lmbda) > 5:
                return None

            return transformed, lmbda
        except Exception:
            return None

    @staticmethod
    def best_fit(values: np.ndarray) -> DistributionFitResult | None:
        """Return the best-fitting distribution (lowest AIC).

        Args:
            values: 1D array of measurement values.

        Returns:
            Best DistributionFitResult or None if fitting fails.
        """
        fits = DistributionFitter.fit_all(values)
        return fits[0] if fits else None


def _params_to_dict(family: str, params: tuple) -> dict[str, float]:
    """Convert scipy distribution parameters to a named dict."""
    if family == "normal":
        return {"loc": float(params[0]), "scale": float(params[1])}
    elif family == "lognormal":
        return {"s": float(params[0]), "loc": float(params[1]), "scale": float(params[2])}
    elif family == "weibull":
        return {"c": float(params[0]), "loc": float(params[1]), "scale": float(params[2])}
    elif family == "gamma":
        return {"a": float(params[0]), "loc": float(params[1]), "scale": float(params[2])}
    elif family == "johnson_su":
        return {
            "a": float(params[0]),
            "b": float(params[1]),
            "loc": float(params[2]),
            "scale": float(params[3]),
        }
    elif family == "johnson_sb":
        return {
            "a": float(params[0]),
            "b": float(params[1]),
            "loc": float(params[2]),
            "scale": float(params[3]),
        }
    else:
        return {f"p{i}": float(p) for i, p in enumerate(params)}


def _dict_to_params(family: str, param_dict: dict[str, float]) -> tuple:
    """Convert a named param dict back to scipy tuple ordering."""
    if family == "normal":
        return (param_dict["loc"], param_dict["scale"])
    elif family == "lognormal":
        return (param_dict["s"], param_dict["loc"], param_dict["scale"])
    elif family == "weibull":
        return (param_dict["c"], param_dict["loc"], param_dict["scale"])
    elif family == "gamma":
        return (param_dict["a"], param_dict["loc"], param_dict["scale"])
    elif family in ("johnson_su", "johnson_sb"):
        return (param_dict["a"], param_dict["b"], param_dict["loc"], param_dict["scale"])
    else:
        return tuple(param_dict.values())


def _get_scipy_dist(family: str):
    """Get scipy distribution object by family name."""
    mapping = {
        "normal": scipy_stats.norm,
        "lognormal": scipy_stats.lognorm,
        "weibull": scipy_stats.weibull_min,
        "gamma": scipy_stats.gamma,
        "johnson_su": scipy_stats.johnsonsu,
        "johnson_sb": scipy_stats.johnsonsb,
    }
    return mapping.get(family)


def compute_qq_points(
    sorted_data: list[float],
    family: str,
    parameters: dict[str, float],
) -> dict[str, list[float]] | None:
    """Compute Q-Q plot points using Blom plotting positions.

    Uses the Blom formula p_i = (i - 3/8) / (n + 1/4) for i = 1..n,
    which is recommended for normal probability plots and generalizes
    well to other distributions.

    Args:
        sorted_data: Sample values sorted in ascending order.
        family: Distribution family name (e.g., "normal", "weibull").
        parameters: Fitted distribution parameters (family-specific dict).

    Returns:
        Dict with "sample_quantiles" and "theoretical_quantiles" lists,
        or None if computation fails.
    """
    dist = _get_scipy_dist(family)
    if dist is None:
        return None

    params = _dict_to_params(family, parameters)
    n = len(sorted_data)
    if n < 2:
        return None

    try:
        # Blom plotting positions: p_i = (i - 3/8) / (n + 1/4)
        # This is the recommended estimator for the i-th order statistic's
        # expected plotting position. Blom (1958) showed these positions
        # minimize the expected squared difference between the plotting
        # position and the true expected value of the order statistic.
        # Ref: Blom, G. (1958), "Statistical Estimates and Transformed
        #      Beta Variables", Wiley.
        positions = [(i - 0.375) / (n + 0.25) for i in range(1, n + 1)]
        theoretical = [float(dist.ppf(p, *params)) for p in positions]

        # Validate: no infinities or NaNs
        if any(not math.isfinite(t) for t in theoretical):
            return None

        return {
            "sample_quantiles": sorted_data,
            "theoretical_quantiles": theoretical,
        }
    except Exception:
        return None


def compute_histogram(values: np.ndarray, n_bins: int = 20) -> HistogramData:
    """Compute histogram from actual measurement data.

    Returns bin edges, counts, and density values for frontend rendering.
    Density = count / (N * bin_width), which integrates to 1 and is
    directly comparable to PDF overlays.
    """
    counts_arr, edges_arr = np.histogram(values, bins=n_bins)
    n_total = len(values)
    bin_width = float(edges_arr[1] - edges_arr[0])

    density = []
    for c in counts_arr:
        d = float(c) / (n_total * bin_width) if bin_width > 0 else 0.0
        density.append(round(d, 8))

    return HistogramData(
        bin_edges=[round(float(e), 6) for e in edges_arr],
        counts=[int(c) for c in counts_arr],
        density=density,
    )


def calculate_percentile_capability(
    values: np.ndarray,
    usl: float | None,
    lsl: float | None,
) -> tuple[float | None, float | None, float, float, float]:
    """Calculate capability using the percentile method (ISO 21747).

    Uses P0.135, P50, P99.865 percentiles (equivalent to +/-3 sigma for normal).

    Pp uses the full spread: Pp = (USL - LSL) / (P99.865 - P0.135)

    Ppk uses the **asymmetric half-spread** method per ISO 21747:2006:
        Ppk = min((USL - P50) / (P99.865 - P50),
                  (P50 - LSL) / (P50 - P0.135))

    This is the more conservative and distribution-aware approach for skewed
    data. It differs from Minitab's symmetric approach which uses
    (P99.865 - P0.135) as denominator throughout. For symmetric distributions,
    both methods give identical results. For skewed distributions, the
    asymmetric method correctly penalizes the tail closer to the spec limit.

    Reference:
        ISO 21747:2006, Section 7 — Percentile method for non-normal capability.

    Args:
        values: 1D array of measurement values.
        usl: Upper specification limit (None if one-sided).
        lsl: Lower specification limit (None if one-sided).

    Returns:
        Tuple of (Pp, Ppk, p0_135, p50, p99_865).
    """
    # The 0.135th and 99.865th percentiles are the non-normal equivalents
    # of mean +/- 3*sigma under normality (Phi(3) = 0.99865, Phi(-3) = 0.00135).
    # P50 (median) replaces the mean for skewed distributions.
    # Ref: ISO 21747:2006, Section 7.
    p0_135 = float(np.percentile(values, 0.135))
    p50 = float(np.percentile(values, 50.0))
    p99_865 = float(np.percentile(values, 99.865))

    spread = p99_865 - p0_135
    pp: float | None = None
    ppk: float | None = None

    if spread <= 0:
        return None, None, p0_135, p50, p99_865

    # Pp: both limits required
    if usl is not None and lsl is not None:
        pp = (usl - lsl) / spread

    # Ppk: asymmetric half-spreads for skewed distributions
    # Upper half-spread = P99.865 - P50, lower half-spread = P50 - P0.135
    upper_half = p99_865 - p50
    lower_half = p50 - p0_135
    ppk_values = []
    if usl is not None and upper_half > 0:
        ppk_values.append((usl - p50) / upper_half)
    if lsl is not None and lower_half > 0:
        ppk_values.append((p50 - lsl) / lower_half)

    if ppk_values:
        ppk = min(ppk_values)

    return (
        _round_or_none(pp),
        _round_or_none(ppk),
        round(p0_135, 6),
        round(p50, 6),
        round(p99_865, 6),
    )


def _box_cox_capability(
    transformed: np.ndarray,
    lmbda: float,
    usl: float | None,
    lsl: float | None,
    target: float | None,
    sigma_within: float | None,
    original_values: np.ndarray | None = None,
) -> tuple[float | None, float | None, float | None, float | None, float | None]:
    """Calculate capability indices on Box-Cox transformed data and spec limits.

    Capability indices (Cp, Cpk, Pp, Ppk) are computed in the transformed
    (approximately normal) space, which is the standard approach per
    ASTM E2587 and Montgomery (2020, Ch. 7).

    Jensen's Inequality Bias — Back-Transformation of the Mean:
    ------------------------------------------------------------
    For the delta method (within-sigma transformation), we need the
    original-scale mean x_bar to compute the Box-Cox derivative. A naive
    approach would back-transform the transformed mean:

        x_bar_naive = g^{-1}(mean(g(X)))

    This is BIASED due to Jensen's inequality:

        E[g^{-1}(Y)] != g^{-1}(E[Y])  for nonlinear g

    For convex g^{-1} (which occurs when lambda < 1, the common case for
    right-skewed manufacturing data like tool wear and surface roughness),
    Jensen's inequality gives:

        E[g^{-1}(Y)] > g^{-1}(E[Y])

    meaning the naive back-transform UNDERESTIMATES the true original-scale
    mean. This biases the derivative used in the delta method, producing a
    systematically incorrect sigma_within_t and thus incorrect Cp/Cpk values.

    FIX: When ``original_values`` is provided (the normal case), we use
    ``np.mean(original_values)`` directly — the sample mean of the original
    data, which is an unbiased estimator of E[X]. No back-transformation
    needed, no Jensen bias.

    For standard deviation, the delta method approximation is acceptable
    because we are transforming sigma (a spread parameter), not inverting
    a nonlinear function of a mean. The delta method error is O(sigma^2),
    which is small when CV < ~30%.

    References:
        - Box, G.E.P. & Cox, D.R. (1964). "An analysis of transformations."
          JRSS-B, 26(2), 211-252.
        - Hernandez, F. & Johnson, R.A. (1980). "The large-sample behavior
          of transformations to normality." JASA, 75(372), 855-861.
          — Analyzes back-transformation bias in Box-Cox.
        - Jensen, J.L.W.V. (1906). "Sur les fonctions convexes et les
          inegalites entre les valeurs moyennes." Acta Math, 30, 175-193.
        - ASTM E2587-16. Non-normal capability analysis approach.
        - Montgomery, D.C. (2020). "Introduction to Statistical Quality
          Control", 8th ed., Ch. 7.

    Args:
        transformed: Box-Cox transformed values (approximately normal).
        lmbda: Box-Cox lambda parameter.
        usl: Upper specification limit (original scale). None if one-sided.
        lsl: Lower specification limit (original scale). None if one-sided.
        target: Process target (original scale).
        sigma_within: Within-subgroup sigma (original scale).
        original_values: Original (untransformed) measurement values. Used
            to compute the unbiased original-scale mean, avoiding Jensen's
            inequality bias in back-transformation. If None, falls back to
            the (biased) inverse-transform approximation.

    Returns:
        Tuple of (cp, cpk, pp, ppk, cpm).
    """
    # Transform spec limits using the Box-Cox power transform:
    #   g(x) = (x^lambda - 1) / lambda   for lambda != 0
    #   g(x) = ln(x)                     for lambda ~= 0
    def transform_limit(val: float) -> float | None:
        if val <= 0:
            return None
        if abs(lmbda) < 1e-10:
            return math.log(val)
        return (val**lmbda - 1.0) / lmbda

    usl_t = transform_limit(usl) if usl is not None else None
    lsl_t = transform_limit(lsl) if lsl is not None else None

    # If transformation of limits failed, can't compute
    if usl is not None and usl_t is None:
        return None, None, None, None, None
    if lsl is not None and lsl_t is None:
        return None, None, None, None, None

    mean_t = float(np.mean(transformed))
    sigma_overall_t = float(np.std(transformed, ddof=1))

    cp: float | None = None
    cpk: float | None = None
    cpm: float | None = None
    pp: float | None = None
    ppk: float | None = None

    # Pp / Ppk (overall) — computed entirely in the transformed space.
    # The transformed data is approximately normal by construction, so
    # standard normal capability formulas apply directly.
    #   Pp  = (USL_t - LSL_t) / (6 * sigma_overall_t)
    #   Ppk = min((USL_t - mean_t) / (3 * sigma_overall_t),
    #             (mean_t - LSL_t) / (3 * sigma_overall_t))
    if sigma_overall_t > 0:
        if usl_t is not None and lsl_t is not None:
            pp = (usl_t - lsl_t) / (6.0 * sigma_overall_t)

        ppk_values = []
        if usl_t is not None:
            ppk_values.append((usl_t - mean_t) / (3.0 * sigma_overall_t))
        if lsl_t is not None:
            ppk_values.append((mean_t - lsl_t) / (3.0 * sigma_overall_t))
        if ppk_values:
            ppk = min(ppk_values)

    # Cp / Cpk (within) — use delta method to transform sigma_within
    #
    # Delta method approximation (first-order Taylor expansion):
    #   Var(g(X)) ≈ [g'(μ)]² * Var(X)
    # where g is the Box-Cox transform.
    #
    # The derivative of the Box-Cox transform y(x) at the original mean x̄ is:
    #   dy/dx = x̄^(λ-1)  (for λ != 0)
    #   dy/dx = 1/x̄       (for λ ≈ 0, i.e. log transform)
    # So σ_within_transformed ≈ σ_within * |x̄^(λ-1)|
    #
    # LIMITATION: This first-order approximation works well when σ is small
    # relative to the mean (CV < ~30%). For large coefficients of variation
    # or extreme lambda values (|λ| > 2), the approximation error can exceed
    # 5% relative error in Cp/Cpk. In such cases, re-estimating sigma on the
    # transformed data would be more accurate, but requires access to the
    # original subgroup structure.
    # Ref: Chou, Owen & Borrego (1990); Montgomery (2020) notes this is
    # "adequate for most practical applications."
    sigma_within_t: float | None = None
    if sigma_within is not None and sigma_within > 0:
        # Compute the original-scale mean for the delta method derivative.
        #
        # JENSEN BIAS FIX: Use np.mean(original_values) when available.
        # This is the unbiased sample mean of the original data — no
        # back-transformation through a nonlinear function, so no
        # Jensen's inequality bias.
        #
        # Previously, this code inverted the Box-Cox transform at mean_t:
        #   x_bar = (lambda * mean_t + 1)^(1/lambda)
        # which is biased because E[g^{-1}(Y)] != g^{-1}(E[Y]).
        # For right-skewed data (lambda < 1), this underestimates x_bar,
        # which inflates the derivative, shrinks sigma_within_t, and
        # makes Cpk appear better than reality.
        #
        # Ref: Hernandez & Johnson (1980); Box & Cox (1964).
        if original_values is not None and len(original_values) > 0:
            # Direct computation — unbiased, no Jensen inequality issue
            x_bar_orig = float(np.mean(original_values))
        else:
            # Fallback: inverse Box-Cox at transformed mean (biased).
            # This path should not be reached in normal operation.
            if abs(lmbda) < 1e-10:
                x_bar_orig = math.exp(mean_t)
            else:
                x_bar_orig = (
                    (lmbda * mean_t + 1.0) ** (1.0 / lmbda)
                    if (lmbda * mean_t + 1.0) > 0
                    else 0.0
                )

        # Compute derivative of Box-Cox transform at x_bar_orig:
        #   g'(x) = x^(lambda-1)   for lambda != 0
        #   g'(x) = 1/x            for lambda ~= 0 (log transform)
        if x_bar_orig > 0:
            if abs(lmbda) < 1e-10:
                deriv = 1.0 / x_bar_orig
            else:
                deriv = abs(x_bar_orig ** (lmbda - 1.0))
        else:
            deriv = 0.0

        sigma_within_t = sigma_within * deriv if deriv > 0 else 0.0

        if sigma_within_t > 0:
            if usl_t is not None and lsl_t is not None:
                cp = (usl_t - lsl_t) / (6.0 * sigma_within_t)

            cpk_values = []
            if usl_t is not None:
                cpk_values.append((usl_t - mean_t) / (3.0 * sigma_within_t))
            if lsl_t is not None:
                cpk_values.append((mean_t - lsl_t) / (3.0 * sigma_within_t))
            if cpk_values:
                cpk = min(cpk_values)

    # Cpm — uses sigma_within per AIAG definition
    #   Cpm = (USL_t - LSL_t) / (6 * tau)
    #   tau = sqrt(sigma_within_t^2 + (mean_t - target_t)^2)
    if cp is not None and target is not None:
        target_t = transform_limit(target) if target > 0 else None
        if target_t is not None and sigma_within_t is not None and sigma_within_t > 0:
            tau = math.sqrt(sigma_within_t**2 + (mean_t - target_t) ** 2)
            if tau > 0 and usl_t is not None and lsl_t is not None:
                cpm = (usl_t - lsl_t) / (6.0 * tau)

    return (
        _round_or_none(cp),
        _round_or_none(cpk),
        _round_or_none(pp),
        _round_or_none(ppk),
        _round_or_none(cpm),
    )


def _distribution_fit_capability(
    fit_result: DistributionFitResult,
    usl: float | None,
    lsl: float | None,
) -> tuple[float | None, float | None]:
    """Calculate Pp/Ppk from a fitted distribution using Z-score method.

    z_USL = Phi^(-1)(F_D(USL; theta))
    z_LSL = Phi^(-1)(F_D(LSL; theta))
    Pp = (z_USL - z_LSL) / 6
    Ppk = min(z_USL / 3, -z_LSL / 3)

    Returns (pp, ppk).
    """
    dist = _get_scipy_dist(fit_result.family)
    if dist is None:
        return None, None

    params = _dict_to_params(fit_result.family, fit_result.parameters)

    z_usl: float | None = None
    z_lsl: float | None = None

    try:
        if usl is not None:
            p_usl = dist.cdf(usl, *params)
            p_usl = max(1e-15, min(1 - 1e-15, p_usl))
            z_usl = float(scipy_stats.norm.ppf(p_usl))

        if lsl is not None:
            p_lsl = dist.cdf(lsl, *params)
            p_lsl = max(1e-15, min(1 - 1e-15, p_lsl))
            z_lsl = float(scipy_stats.norm.ppf(p_lsl))
    except Exception:
        return None, None

    pp: float | None = None
    ppk: float | None = None

    if z_usl is not None and z_lsl is not None:
        pp = (z_usl - z_lsl) / 6.0

    ppk_values = []
    if z_usl is not None:
        ppk_values.append(z_usl / 3.0)
    if z_lsl is not None:
        ppk_values.append(-z_lsl / 3.0)
    if ppk_values:
        ppk = min(ppk_values)

    return _round_or_none(pp), _round_or_none(ppk)


def calculate_capability_nonnormal(
    values: list[float],
    usl: float | None,
    lsl: float | None,
    target: float | None = None,
    sigma_within: float | None = None,
    method: str = "auto",
    distribution_params: dict[str, str | float] | None = None,
    collector: "ExplanationCollector | None" = None,
) -> NonNormalCapabilityResult:
    """Calculate process capability using non-normal methods.

    Auto-cascade order:
    1. Shapiro-Wilk normality test (p >= 0.05 -> use normal method)
    2. Box-Cox transformation
    3. Distribution fitting (best AIC)
    4. Percentile fallback

    Args:
        values: Individual measurement values.
        usl: Upper specification limit. None if one-sided.
        lsl: Lower specification limit. None if one-sided.
        target: Process target value.
        sigma_within: Within-subgroup sigma.
        method: "auto", "normal", "box_cox", "percentile", or "distribution_fit".
        distribution_params: Optional dict to force a specific family (e.g., {"family": "weibull"}).
        collector: Optional ExplanationCollector for Show Your Work support.

    Returns:
        NonNormalCapabilityResult with all computed indices.

    Raises:
        ValueError: If fewer than 2 values or both limits are None.
    """
    if len(values) < 2:
        raise ValueError(f"Need at least 2 values, got {len(values)}")

    if usl is None and lsl is None:
        raise ValueError("At least one specification limit (USL or LSL) must be provided")

    if usl is not None and lsl is not None and usl <= lsl:
        raise ValueError(f"USL ({usl}) must be greater than LSL ({lsl})")

    arr = np.asarray(values, dtype=np.float64)
    n = len(values)
    now = datetime.now(timezone.utc)

    if collector:
        collector.input("n", n)
        collector.input("method", method)
        if usl is not None:
            collector.input("USL", usl)
        if lsl is not None:
            collector.input("LSL", lsl)

    # Default target to midpoint
    if target is None and usl is not None and lsl is not None:
        target = (usl + lsl) / 2.0

    # All values identical -> can't compute meaningful capability
    if np.std(arr) == 0:
        pct_pp, pct_ppk, p0, p50, p99 = calculate_percentile_capability(arr, usl, lsl)
        return NonNormalCapabilityResult(
            cp=None, cpk=None, pp=None, ppk=None, cpm=None,
            method=method, method_detail="Constant data (sigma=0)",
            normality_p_value=None, normality_test="skipped", is_normal=False,
            fitted_distribution=None,
            percentile_pp=pct_pp, percentile_ppk=pct_ppk,
            p0_135=p0, p50=p50, p99_865=p99,
            sample_count=n, calculated_at=now,
            histogram=compute_histogram(arr),
        )

    # Normality test (Shapiro-Wilk, max 5000 samples)
    normality_p: float | None = None
    normality_test = "shapiro_wilk"
    is_normal = False
    if n >= 3:
        # Shapiro-Wilk limit is 5000 samples; use random subset to avoid bias
        if n > 5000:
            rng = np.random.default_rng(42)
            test_sample = rng.choice(arr, size=5000, replace=False)
        else:
            test_sample = arr
        try:
            result = scipy_stats.shapiro(test_sample)
            normality_p = float(result.pvalue)
            is_normal = normality_p >= 0.05
            if collector:
                geq_sym = r"\geq" if is_normal else "<"
                collector.step(
                    label="Normality Test (Shapiro-Wilk)",
                    formula_latex=r"H_0: \text{Data is normally distributed}",
                    substitution_latex=rf"p = {normality_p:.6f} {geq_sym} 0.05",
                    result=normality_p,
                    note="Normal" if is_normal else "Non-normal distribution detected",
                )
        except Exception:
            normality_test = "failed"

    # Always compute percentile for comparison
    pct_pp, pct_ppk, p0_135, p50, p99_865 = calculate_percentile_capability(arr, usl, lsl)
    if collector and (pct_pp is not None or pct_ppk is not None):
        collector.step(
            label="Percentile capability (reference)",
            formula_latex=r"P_p = \frac{USL - LSL}{P_{99.865} - P_{0.135}}",
            substitution_latex=rf"P_{{0.135}}={p0_135:.4f}, P_{{50}}={p50:.4f}, P_{{99.865}}={p99_865:.4f}",
            result=pct_pp,
            note="ISO 21747 percentile method — always computed for comparison",
        )

    # Compute histogram from actual measurement data (BLOCKER-1 fix)
    hist_data = compute_histogram(arr)

    # ---- Method selection ----
    cp: float | None = None
    cpk: float | None = None
    pp: float | None = None
    ppk: float | None = None
    cpm: float | None = None
    method_detail = ""
    fitted_dist: DistributionFitResult | None = None

    if method == "normal" or (method == "auto" and is_normal):
        # Use standard normal capability
        from cassini.core.capability import calculate_capability

        normal_result = calculate_capability(values, usl, lsl, target, sigma_within, collector=collector)
        # For normal data, compute Q-Q against normal distribution
        sorted_vals = sorted(values)
        normal_params = {"loc": float(np.mean(arr)), "scale": float(np.std(arr, ddof=1))}
        qq = compute_qq_points(sorted_vals, "normal", normal_params)
        return NonNormalCapabilityResult(
            cp=normal_result.cp, cpk=normal_result.cpk,
            pp=normal_result.pp, ppk=normal_result.ppk,
            cpm=normal_result.cpm,
            method="normal", method_detail="Normal (Shapiro-Wilk passed)",
            normality_p_value=_round_or_none(normality_p, 6),
            normality_test=normality_test, is_normal=is_normal,
            fitted_distribution=None,
            percentile_pp=pct_pp, percentile_ppk=pct_ppk,
            p0_135=p0_135, p50=p50, p99_865=p99_865,
            sample_count=n, calculated_at=now,
            histogram=hist_data,
            qq_points=qq,
        )

    if method == "box_cox" or (method == "auto" and not is_normal):
        bc_result = DistributionFitter.fit_box_cox(arr)
        if bc_result is not None:
            transformed, lmbda = bc_result
            if collector:
                collector.step(
                    label="Box-Cox transformation",
                    formula_latex=r"y = \frac{x^\lambda - 1}{\lambda}" if lmbda != 0 else r"y = \ln(x)",
                    substitution_latex=rf"\lambda = {lmbda:.4f}",
                    result=lmbda,
                    note="Optimal lambda found via MLE (scipy.stats.boxcox)",
                )
            cp, cpk, pp, ppk, cpm = _box_cox_capability(
                transformed, lmbda, usl, lsl, target, sigma_within,
                original_values=arr,  # Jensen bias fix: pass original data
            )
            if pp is not None or ppk is not None:
                method_detail = f"Box-Cox (lambda={lmbda:.4f})"
                # Q-Q for Box-Cox: use normal Q-Q since transformed data should be normal
                sorted_vals = sorted(values)
                normal_params = {"loc": float(np.mean(arr)), "scale": float(np.std(arr, ddof=1))}
                qq = compute_qq_points(sorted_vals, "normal", normal_params)
                return NonNormalCapabilityResult(
                    cp=cp, cpk=cpk, pp=pp, ppk=ppk, cpm=cpm,
                    method="box_cox", method_detail=method_detail,
                    normality_p_value=_round_or_none(normality_p, 6),
                    normality_test=normality_test, is_normal=is_normal,
                    fitted_distribution=None,
                    percentile_pp=pct_pp, percentile_ppk=pct_ppk,
                    p0_135=p0_135, p50=p50, p99_865=p99_865,
                    sample_count=n, calculated_at=now,
                    histogram=hist_data,
                    qq_points=qq,
                )

        # Box-Cox failed or was not requested as the sole method
        if method == "box_cox":
            # Fall through to percentile if box_cox specifically requested but failed
            return NonNormalCapabilityResult(
                cp=None, cpk=None, pp=pct_pp, ppk=pct_ppk, cpm=None,
                method="percentile",
                method_detail="Percentile (Box-Cox failed, data may have non-positive values)",
                normality_p_value=_round_or_none(normality_p, 6),
                normality_test=normality_test, is_normal=is_normal,
                fitted_distribution=None,
                percentile_pp=pct_pp, percentile_ppk=pct_ppk,
                p0_135=p0_135, p50=p50, p99_865=p99_865,
                sample_count=n, calculated_at=now,
                histogram=hist_data,
            )

    if method == "distribution_fit" or (method == "auto" and not is_normal):
        # If the user explicitly saved a specific family (e.g., {"family": "weibull"}), 
        # force the fit to that exact family, ignoring AIC ranking for others.
        target_family = distribution_params.get("family") if distribution_params else None

        if n >= 8:
            requested_fits = []
            if target_family:
                # Force fit only the requested family
                for name, dist, n_params in DistributionFitter.FAMILIES:
                    if name == target_family:
                        try:
                            # MLE fit
                            params = dist.fit(arr)
                            gof_stat, gof_p, is_adequate, test_type = _anderson_darling_test(dist, params, arr)
                            ll = _log_likelihood(dist, params, arr)
                            aic = _compute_aic(len(arr), n_params, ll)
                            param_dict = _params_to_dict(name, params)

                            forced_fit = DistributionFitResult(
                                family=name,
                                parameters=param_dict,
                                ad_statistic=round(gof_stat, 6),
                                ad_p_value=_round_or_none(gof_p, 6),
                                aic=round(aic, 2),
                                is_adequate_fit=is_adequate,
                                gof_test_type=test_type,
                            )
                            requested_fits.append(forced_fit)
                        except Exception:
                            pass
                        break
                best = requested_fits[0] if requested_fits else None
            else:
                # Normal auto-cascade (pick best by AIC)
                best = DistributionFitter.best_fit(arr)

            if best is not None:
                fitted_dist = best
                pp, ppk = _distribution_fit_capability(best, usl, lsl)
                if pp is not None or ppk is not None:
                    # Compute Q-Q points for the fitted distribution
                    sorted_vals = sorted(values)
                    qq = compute_qq_points(sorted_vals, best.family, best.parameters)
                    # Provide clearer detail if a fit was explicitly forced vs auto-selected
                    prefix = "Forced" if target_family else "Auto-selected"
                    method_detail = f"{prefix} {best.family.replace('_', ' ').title()} fit (AIC={best.aic:.1f})"
                    return NonNormalCapabilityResult(
                        cp=None, cpk=None, pp=pp, ppk=ppk, cpm=None,
                        method="distribution_fit", method_detail=method_detail,
                        normality_p_value=_round_or_none(normality_p, 6),
                        normality_test=normality_test, is_normal=is_normal,
                        fitted_distribution=fitted_dist,
                        percentile_pp=pct_pp, percentile_ppk=pct_ppk,
                        p0_135=p0_135, p50=p50, p99_865=p99_865,
                        sample_count=n, calculated_at=now,
                        histogram=hist_data,
                        qq_points=qq,
                    )

        if method == "distribution_fit":
            # Specifically requested but no fit could be generated
            reason = f"for requested family '{target_family}'" if target_family else "found"
            return NonNormalCapabilityResult(
                cp=None, cpk=None, pp=pct_pp, ppk=pct_ppk, cpm=None,
                method="percentile",
                method_detail=f"Percentile (no adequate distribution fit {reason})",
                normality_p_value=_round_or_none(normality_p, 6),
                normality_test=normality_test, is_normal=is_normal,
                fitted_distribution=fitted_dist,
                percentile_pp=pct_pp, percentile_ppk=pct_ppk,
                p0_135=p0_135, p50=p50, p99_865=p99_865,
                sample_count=n, calculated_at=now,
                histogram=hist_data,
            )

    # Percentile fallback (method == "percentile" or auto cascade exhausted)
    return NonNormalCapabilityResult(
        cp=None, cpk=None, pp=pct_pp, ppk=pct_ppk, cpm=None,
        method="percentile", method_detail="Percentile (P0.135 / P99.865)",
        normality_p_value=_round_or_none(normality_p, 6),
        normality_test=normality_test, is_normal=is_normal,
        fitted_distribution=fitted_dist,
        percentile_pp=pct_pp, percentile_ppk=pct_ppk,
        p0_135=p0_135, p50=p50, p99_865=p99_865,
        sample_count=n, calculated_at=now,
        histogram=hist_data,
    )
