"""AS9102 Rev C FAI report export — PDF and Excel.

Generates First Article Inspection documents conforming to AS9102 Rev C
form layouts (Form 1: Part Number Accountability, Form 2: Product
Accountability, Form 3: Characteristic Accountability).

PDF generation uses fpdf2 (MIT-licensed).
Excel generation uses openpyxl with three worksheets.
"""

from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any

from fpdf import FPDF
from fpdf.enums import XPos, YPos
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

if TYPE_CHECKING:
    pass

# ---------------------------------------------------------------------------
# Styling constants
# ---------------------------------------------------------------------------

_HEADER_FILL = PatternFill(start_color="2F5496", end_color="2F5496", fill_type="solid")
_HEADER_FONT = Font(bold=True, color="FFFFFF", size=10)
_TITLE_FONT = Font(bold=True, size=14, color="2F5496")
_SUBTITLE_FONT = Font(bold=True, size=11, color="2F5496")
_CELL_ALIGNMENT = Alignment(horizontal="left", vertical="center", wrap_text=True)
_CENTER_ALIGNMENT = Alignment(horizontal="center", vertical="center", wrap_text=True)
_THIN_BORDER = Border(
    left=Side(style="thin"),
    right=Side(style="thin"),
    top=Side(style="thin"),
    bottom=Side(style="thin"),
)
_PASS_FILL = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
_FAIL_FILL = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")
_DEVIATION_FILL = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")


def _result_fill(result: str) -> PatternFill | None:
    if result == "pass":
        return _PASS_FILL
    elif result == "fail":
        return _FAIL_FILL
    elif result == "deviation":
        return _DEVIATION_FILL
    return None


def _safe_str(val: Any) -> str:
    """Convert a value to a display string, handling None."""
    if val is None:
        return ""
    return str(val)


def _format_datetime(val: datetime | str | None) -> str:
    """Format a datetime for display."""
    if val is None:
        return ""
    if isinstance(val, str):
        return val[:19].replace("T", " ")
    return val.strftime("%Y-%m-%d %H:%M")


# ===========================================================================
# PDF Export (fpdf2)
# ===========================================================================


class _AS9102PDF(FPDF):
    """Custom FPDF subclass for AS9102 report layout."""

    def __init__(self, report_data: dict) -> None:
        super().__init__(orientation="L", unit="mm", format="A4")
        self._report = report_data
        self.set_auto_page_break(auto=True, margin=20)

    def header(self) -> None:
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 8, "AS9102 First Article Inspection Report",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.set_font("Helvetica", "", 8)
        part = _safe_str(self._report.get("part_number"))
        rev = _safe_str(self._report.get("revision"))
        fai_type = _safe_str(self._report.get("fai_type", "full")).upper()
        self.cell(
            0, 5,
            f"Part: {part}  Rev: {rev}  |  Type: {fai_type}  |  Status: {_safe_str(self._report.get('status', '')).upper()}",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C",
        )
        self.ln(3)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="C")
        self.set_y(-10)
        self.cell(0, 5, "Generated by Cassini SPC", align="C")


def _pdf_section_title(pdf: _AS9102PDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(47, 84, 150)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 7, f"  {title}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)


def _pdf_key_value_row(pdf: _AS9102PDF, label: str, value: str, w_label: int = 50) -> None:
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(w_label, 5, label, border=1)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 5, value, border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def _pdf_table_header(pdf: _AS9102PDF, headers: list[tuple[str, int]]) -> None:
    pdf.set_font("Helvetica", "B", 7)
    pdf.set_fill_color(47, 84, 150)
    pdf.set_text_color(255, 255, 255)
    for label, w in headers:
        pdf.cell(w, 6, label, border=1, fill=True, align="C")
    pdf.ln()
    pdf.set_text_color(0, 0, 0)


def _pdf_table_row(pdf: _AS9102PDF, cells: list[tuple[str, int]], result: str | None = None) -> None:
    pdf.set_font("Helvetica", "", 7)
    if result == "fail":
        pdf.set_fill_color(255, 199, 206)
    elif result == "deviation":
        pdf.set_fill_color(255, 235, 156)
    elif result == "pass":
        pdf.set_fill_color(198, 239, 206)
    else:
        pdf.set_fill_color(255, 255, 255)

    fill = result is not None
    for text, w in cells:
        pdf.cell(w, 5, text[:60], border=1, fill=fill, align="C")
    pdf.ln()


def generate_fai_pdf(report_data: dict) -> bytes:
    """Generate an AS9102 Rev C PDF from structured report data.

    Parameters
    ----------
    report_data : dict
        Full report data including form1/form2/form3 sections plus
        items, materials, special_processes_items, functional_tests_items.

    Returns
    -------
    bytes
        PDF file content.
    """
    pdf = _AS9102PDF(report_data)
    pdf.alias_nb_pages()
    pdf.add_page()

    # ── Form 1: Part Number Accountability ──────────────────────
    _pdf_section_title(pdf, "FORM 1 - Part Number Accountability")

    fields = [
        ("Part Number", _safe_str(report_data.get("part_number"))),
        ("Part Name", _safe_str(report_data.get("part_name"))),
        ("Drawing Number", _safe_str(report_data.get("drawing_number"))),
        ("Revision", _safe_str(report_data.get("revision"))),
        ("Serial Number", _safe_str(report_data.get("serial_number"))),
        ("Lot Number", _safe_str(report_data.get("lot_number"))),
        ("Organization", _safe_str(report_data.get("organization_name"))),
        ("Supplier", _safe_str(report_data.get("supplier"))),
        ("Purchase Order", _safe_str(report_data.get("purchase_order"))),
        ("Reason for Inspection", _safe_str(report_data.get("reason_for_inspection"))),
        ("FAI Type", _safe_str(report_data.get("fai_type", "full")).upper()),
    ]

    for label, value in fields:
        _pdf_key_value_row(pdf, label, value)

    pdf.ln(3)

    # Signature block
    _pdf_section_title(pdf, "SIGNATURES")
    _pdf_key_value_row(pdf, "Created By", f"User #{_safe_str(report_data.get('created_by'))}", 40)
    _pdf_key_value_row(pdf, "Created At", _format_datetime(report_data.get("created_at")), 40)
    _pdf_key_value_row(pdf, "Submitted By", f"User #{_safe_str(report_data.get('submitted_by'))}", 40)
    _pdf_key_value_row(pdf, "Submitted At", _format_datetime(report_data.get("submitted_at")), 40)
    _pdf_key_value_row(pdf, "Approved By", f"User #{_safe_str(report_data.get('approved_by'))}", 40)
    _pdf_key_value_row(pdf, "Approved At", _format_datetime(report_data.get("approved_at")), 40)

    # ── Form 2: Product Accountability ──────────────────────────
    pdf.add_page()
    _pdf_section_title(pdf, "FORM 2 - Product Accountability")

    # Materials
    materials = report_data.get("materials", [])
    if materials:
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, "Materials:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        headers = [("Part Number", 50), ("Spec", 50), ("Cert #", 40), ("Supplier", 55), ("Result", 25)]
        _pdf_table_header(pdf, headers)
        for m in materials:
            _pdf_table_row(pdf, [
                (_safe_str(m.get("material_part_number")), 50),
                (_safe_str(m.get("material_spec")), 50),
                (_safe_str(m.get("cert_number")), 40),
                (_safe_str(m.get("supplier")), 55),
                (_safe_str(m.get("result", "")).upper(), 25),
            ], result=m.get("result"))
        pdf.ln(3)

    # Special Processes
    processes = report_data.get("special_processes_items", [])
    if processes:
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, "Special Processes:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        headers = [("Process", 55), ("Spec", 50), ("Cert #", 40), ("Approved Supplier", 50), ("Result", 25)]
        _pdf_table_header(pdf, headers)
        for sp in processes:
            _pdf_table_row(pdf, [
                (_safe_str(sp.get("process_name")), 55),
                (_safe_str(sp.get("process_spec")), 50),
                (_safe_str(sp.get("cert_number")), 40),
                (_safe_str(sp.get("approved_supplier")), 50),
                (_safe_str(sp.get("result", "")).upper(), 25),
            ], result=sp.get("result"))
        pdf.ln(3)

    # Functional Tests
    tests = report_data.get("functional_tests_items", [])
    if tests:
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(0, 5, "Functional Tests:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        headers = [("Description", 80), ("Procedure #", 50), ("Actual Results", 60), ("Result", 25)]
        _pdf_table_header(pdf, headers)
        for ft in tests:
            _pdf_table_row(pdf, [
                (_safe_str(ft.get("test_description")), 80),
                (_safe_str(ft.get("procedure_number")), 50),
                (_safe_str(ft.get("actual_results")), 60),
                (_safe_str(ft.get("result", "")).upper(), 25),
            ], result=ft.get("result"))

    # ── Form 3: Characteristic Accountability ───────────────────
    pdf.add_page()
    _pdf_section_title(pdf, "FORM 3 - Characteristic Accountability")

    items = report_data.get("items", [])

    # Summary
    total = len(items)
    pass_count = sum(1 for i in items if i.get("result") == "pass")
    fail_count = sum(1 for i in items if i.get("result") == "fail")
    deviation_count = sum(1 for i in items if i.get("result") == "deviation")

    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 5, f"Total: {total}  |  Pass: {pass_count}  |  Fail: {fail_count}  |  Deviation: {deviation_count}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    if items:
        headers = [
            ("Bal#", 12), ("Characteristic", 45), ("Zone", 15),
            ("Nominal", 20), ("LSL", 20), ("USL", 20),
            ("Actual", 25), ("Unit", 12), ("Tools", 30),
            ("DC", 10), ("Result", 15),
        ]
        # Check if any items are carried forward (delta FAI)
        has_cf = any(i.get("carried_forward") for i in items)
        if has_cf:
            headers.append(("CF", 10))

        _pdf_table_header(pdf, headers)

        for item in items:
            # Determine actual value display
            if item.get("value_type") == "text":
                actual_display = _safe_str(item.get("actual_value_text"))
            elif item.get("value_type") == "pass_fail":
                actual_display = _safe_str(item.get("actual_value_text", item.get("result")))
            else:
                actual_display = _safe_str(item.get("actual_value"))

            cells = [
                (str(item.get("balloon_number", "")), 12),
                (_safe_str(item.get("characteristic_name")), 45),
                (_safe_str(item.get("drawing_zone")), 15),
                (_safe_str(item.get("nominal")), 20),
                (_safe_str(item.get("lsl")), 20),
                (_safe_str(item.get("usl")), 20),
                (actual_display, 25),
                (_safe_str(item.get("unit")), 12),
                (_safe_str(item.get("tools_used")), 30),
                ("Y" if item.get("designed_char") else "", 10),
                (_safe_str(item.get("result", "")).upper(), 15),
            ]
            if has_cf:
                cells.append(("Y" if item.get("carried_forward") else "", 10))

            _pdf_table_row(pdf, cells, result=item.get("result"))

    buf = io.BytesIO()
    pdf.output(buf)
    return buf.getvalue()


# ===========================================================================
# Excel Export (openpyxl)
# ===========================================================================


def _xl_write_header(ws, row: int, headers: list[str]) -> int:
    """Write a header row with styling. Returns next row."""
    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=row, column=col_idx, value=header)
        cell.font = _HEADER_FONT
        cell.fill = _HEADER_FILL
        cell.alignment = _CENTER_ALIGNMENT
        cell.border = _THIN_BORDER
    return row + 1


def _xl_write_row(ws, row: int, values: list[Any], result: str | None = None) -> int:
    """Write a data row with optional result-based fill. Returns next row."""
    fill = _result_fill(result) if result else None
    for col_idx, val in enumerate(values, 1):
        cell = ws.cell(row=row, column=col_idx, value=val)
        cell.alignment = _CELL_ALIGNMENT
        cell.border = _THIN_BORDER
        if fill:
            cell.fill = fill
    return row + 1


def _xl_write_kv(ws, row: int, label: str, value: Any) -> int:
    """Write a key-value pair across two columns. Returns next row."""
    label_cell = ws.cell(row=row, column=1, value=label)
    label_cell.font = Font(bold=True, size=10)
    label_cell.border = _THIN_BORDER
    value_cell = ws.cell(row=row, column=2, value=_safe_str(value))
    value_cell.border = _THIN_BORDER
    return row + 1


def generate_fai_excel(report_data: dict) -> bytes:
    """Generate an AS9102 Rev C Excel workbook from structured report data.

    Returns an xlsx file as bytes with three sheets:
    - Form 1: Part Number Accountability
    - Form 2: Product Accountability
    - Form 3: Characteristic Accountability

    Parameters
    ----------
    report_data : dict
        Full report data.

    Returns
    -------
    bytes
        XLSX file content.
    """
    wb = Workbook()

    # ── Form 1: Part Number Accountability ──────────────────────
    ws1 = wb.active
    ws1.title = "Form 1 - Part Accountability"

    ws1.cell(row=1, column=1, value="AS9102 Form 1 — Part Number Accountability").font = _TITLE_FONT
    ws1.merge_cells("A1:B1")

    row = 3
    fields = [
        ("Part Number", report_data.get("part_number")),
        ("Part Name", report_data.get("part_name")),
        ("Drawing Number", report_data.get("drawing_number")),
        ("Revision", report_data.get("revision")),
        ("Serial Number", report_data.get("serial_number")),
        ("Lot Number", report_data.get("lot_number")),
        ("Organization", report_data.get("organization_name")),
        ("Supplier", report_data.get("supplier")),
        ("Purchase Order", report_data.get("purchase_order")),
        ("Reason for Inspection", report_data.get("reason_for_inspection")),
        ("FAI Type", _safe_str(report_data.get("fai_type", "full")).upper()),
        ("Status", _safe_str(report_data.get("status", "")).upper()),
    ]
    for label, value in fields:
        row = _xl_write_kv(ws1, row, label, value)

    # Signature block
    row += 1
    ws1.cell(row=row, column=1, value="Signatures").font = _SUBTITLE_FONT
    row += 1
    sig_fields = [
        ("Created By", f"User #{_safe_str(report_data.get('created_by'))}"),
        ("Created At", _format_datetime(report_data.get("created_at"))),
        ("Submitted By", f"User #{_safe_str(report_data.get('submitted_by'))}"),
        ("Submitted At", _format_datetime(report_data.get("submitted_at"))),
        ("Approved By", f"User #{_safe_str(report_data.get('approved_by'))}"),
        ("Approved At", _format_datetime(report_data.get("approved_at"))),
    ]
    for label, value in sig_fields:
        row = _xl_write_kv(ws1, row, label, value)

    # Delta FAI info if present
    if report_data.get("parent_report_id"):
        row += 1
        ws1.cell(row=row, column=1, value="Delta FAI Information").font = _SUBTITLE_FONT
        row += 1
        row = _xl_write_kv(ws1, row, "Parent Report ID", report_data.get("parent_report_id"))

    ws1.column_dimensions["A"].width = 25
    ws1.column_dimensions["B"].width = 45

    # ── Form 2: Product Accountability ──────────────────────────
    ws2 = wb.create_sheet("Form 2 - Product Accountability")

    ws2.cell(row=1, column=1, value="AS9102 Form 2 — Product Accountability").font = _TITLE_FONT
    ws2.merge_cells("A1:E1")

    row = 3

    # Materials
    materials = report_data.get("materials", [])
    ws2.cell(row=row, column=1, value="Materials").font = _SUBTITLE_FONT
    row += 1
    row = _xl_write_header(ws2, row, [
        "Part Number", "Material Spec", "Cert Number", "Supplier", "Result",
    ])
    for m in materials:
        row = _xl_write_row(ws2, row, [
            m.get("material_part_number"),
            m.get("material_spec"),
            m.get("cert_number"),
            m.get("supplier"),
            _safe_str(m.get("result", "")).upper(),
        ], result=m.get("result"))

    row += 1

    # Special Processes
    processes = report_data.get("special_processes_items", [])
    ws2.cell(row=row, column=1, value="Special Processes").font = _SUBTITLE_FONT
    row += 1
    row = _xl_write_header(ws2, row, [
        "Process Name", "Process Spec", "Cert Number", "Approved Supplier", "Result",
    ])
    for sp in processes:
        row = _xl_write_row(ws2, row, [
            sp.get("process_name"),
            sp.get("process_spec"),
            sp.get("cert_number"),
            sp.get("approved_supplier"),
            _safe_str(sp.get("result", "")).upper(),
        ], result=sp.get("result"))

    row += 1

    # Functional Tests
    tests = report_data.get("functional_tests_items", [])
    ws2.cell(row=row, column=1, value="Functional Tests").font = _SUBTITLE_FONT
    row += 1
    row = _xl_write_header(ws2, row, [
        "Test Description", "Procedure Number", "Actual Results", "Result",
    ])
    for ft in tests:
        row = _xl_write_row(ws2, row, [
            ft.get("test_description"),
            ft.get("procedure_number"),
            ft.get("actual_results"),
            _safe_str(ft.get("result", "")).upper(),
        ], result=ft.get("result"))

    for col_letter in ["A", "B", "C", "D", "E"]:
        ws2.column_dimensions[col_letter].width = 25

    # ── Form 3: Characteristic Accountability ───────────────────
    ws3 = wb.create_sheet("Form 3 - Characteristics")

    ws3.cell(row=1, column=1, value="AS9102 Form 3 — Characteristic Accountability").font = _TITLE_FONT
    ws3.merge_cells("A1:K1")

    items = report_data.get("items", [])

    # Summary
    total = len(items)
    pass_count = sum(1 for i in items if i.get("result") == "pass")
    fail_count = sum(1 for i in items if i.get("result") == "fail")
    deviation_count = sum(1 for i in items if i.get("result") == "deviation")

    row = 3
    row = _xl_write_kv(ws3, row, "Total Characteristics", total)
    row = _xl_write_kv(ws3, row, "Pass", pass_count)
    row = _xl_write_kv(ws3, row, "Fail", fail_count)
    row = _xl_write_kv(ws3, row, "Deviation", deviation_count)

    row += 1

    # Check if delta FAI with carried_forward items
    has_cf = any(i.get("carried_forward") for i in items)

    headers = [
        "Bal#", "Characteristic", "Zone", "Nominal",
        "LSL", "USL", "Actual Value", "Unit", "Tools Used",
        "Design Char", "Result",
    ]
    if has_cf:
        headers.append("Carried Forward")

    row = _xl_write_header(ws3, row, headers)

    for item in items:
        # Determine actual value display
        if item.get("value_type") == "text":
            actual_display = item.get("actual_value_text", "")
        elif item.get("value_type") == "pass_fail":
            actual_display = item.get("actual_value_text", item.get("result", ""))
        else:
            actual_display = item.get("actual_value")

        values = [
            item.get("balloon_number"),
            item.get("characteristic_name"),
            item.get("drawing_zone"),
            item.get("nominal"),
            item.get("lsl"),
            item.get("usl"),
            actual_display,
            item.get("unit"),
            item.get("tools_used"),
            "Yes" if item.get("designed_char") else "No",
            _safe_str(item.get("result", "")).upper(),
        ]
        if has_cf:
            values.append("Yes" if item.get("carried_forward") else "No")

        row = _xl_write_row(ws3, row, values, result=item.get("result"))

    # Set column widths
    col_widths = [8, 30, 10, 12, 12, 12, 15, 8, 20, 12, 10]
    if has_cf:
        col_widths.append(15)
    for i, width in enumerate(col_widths):
        from openpyxl.utils import get_column_letter
        ws3.column_dimensions[get_column_letter(i + 1)].width = width

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
